### ISSUE TITLE
Game Repair Behavior on Genshin

### ISSUE THREAD

**Issue by Azusfin** [neon-nyan/Collapse#101]
_Just a question_

i just updated collapse launcher to 1.69.8 today 
before i started the game, i decided to check for broken files just in case
but i found something weird

![game repair](https://user-images.githubusercontent.com/96245167/232290374-b9d50312-2542-413b-af93-c847ccfcd494.png)
it seems to want me to redownload the english audio pack (?)
the size was too big so i managed to ignore it
i logged on to the game then enter the game just fine
the character voices were also not affected

**Was that an intended behavior to redownload the audio pack?**

**Comment by neon-nyan** [comment]
Hi there,

A quick question, Are you using English Audio pack as your main?
And can you show me the content inside of this file?
```
GenshinImpact_Data\Persistent\audio_lang_14
```

**Comment by Azusfin** [comment]
> Hi there,
> 
> A quick question, Are you using English Audio pack as your main Audio pack? And can you show me the content inside of this file?
> 
> ```
> GenshinImpact_Data\Persistent\audio_lang_14
> ```

yep
![audio_lang_14](https://user-images.githubusercontent.com/96245167/232291562-597b289a-081d-4a60-b5ea-b743407378dc.png)

**Comment by neon-nyan** [comment]
Okay, one more question.
Do you have this ``SFX_3.6_0.pck`` file and ``English(US)`` folder inside this folder?
```
GenshinImpact_Data\Persistent\AudioAssets
```

<img width="565" alt="image" src="https://user-images.githubusercontent.com/30566970/232295595-e6f17bb6-1a17-4d68-903b-a33789178ad0.png">

If the ``English(US)`` folder does exist, does the folder have the audio files (``.pck``) inside?
<img width="572" alt="image" src="https://user-images.githubusercontent.com/30566970/232296095-37666cb3-b28d-4311-9fa1-87661c308fbf.png">

**Comment by Azusfin** [comment]
only `SFX_3.6_0.pck` is present
![audioassets](https://user-images.githubusercontent.com/96245167/232298840-3c68cb70-235c-4e14-95f5-2c1ec431afd3.png)

**Comment by neon-nyan** [comment]
Got it and how about the folder below? Does it have ``English(US)`` folder?
```
GenshinImpact_Data\StreamingAssets\AudioAssets
```

**Comment by Azusfin** [comment]
![audioassets](https://user-images.githubusercontent.com/96245167/232302460-3a8c4041-14e7-4a36-acdd-c2e17c64bd7d.png)
![englishus](https://user-images.githubusercontent.com/96245167/232302470-04cc3500-2e16-4aea-a786-556b6595f543.png)

**Comment by neon-nyan** [comment]
Okay, After investigating it further, turns out that Collapse still uses the old mechanism of how the English Audio pack files should be located, which is reading at two different locations. One is from ``StreamingAssets\AudioAssets`` and the second is from ``Persistent\AudioAssets``.

In recent version of Genshin, the game will accept the package either from one of those locations since the game is recognizing both locations are the same.

A fix is still underway and hope we can push a patch for this soon.
