### ISSUE TITLE
extract packadge goes wrong it seems

### ISSUE THREAD

**Issue by ibeez11** [neon-nyan/Collapse#102]
hi it's me again :))
i found this after re-downloading
![image](https://user-images.githubusercontent.com/81704406/232303193-a98ba3c7-fe1d-46e2-80a4-b332538c0029.png)
any idea?? .-.

**Comment by neon-nyan** [comment]
May I know which version do you have right now?
Is it 1.69.7 or 1.69.8?

**Comment by ibeez11** [comment]
![image](https://user-images.githubusercontent.com/81704406/232307638-e970e338-0a7c-4449-879c-d7e8541632ee.png)
1.69.8, the newest, i think i upgrade the launcher around this morning after it release

**Comment by neon-nyan** [comment]
Alright, we found this issue as a bug in recent version (1.69.8)
We are currently fixing this and hopefully, get a patch pushed very soon.

**Comment by neon-nyan** [comment]
Hi @ibeez11,

A new patch 1.69.10 already pushed with the fix for your issue.
Please your update your launcher and try again

**Comment by ibeez11** [comment]
alright, i got that update notification, thanks a lot for the information :))
hope there's will be less bug so u and ur team can take a rest :))
