### ISSUE TITLE
how to fix fatal error on app level?

### ISSUE THREAD

**Issue by Miracle1x** [neon-nyan/Collapse#103]
After the update, this keeps showing up
![image_2023-04-16_200937174](https://user-images.githubusercontent.com/130907056/232308888-e971b5ac-1d86-4012-86e1-f418ece93c61.png)

**Comment by bagusnl** [comment]
It seems that the update process is failed since we changed quite a lot about the Launcher structure and update process lately. While we investigate the issue, you could go ahead and install the new version directly from the Releases section to continue using Collapse.
