### ISSUE TITLE
Support for Korean

### ISSUE THREAD

**Issue by koori0831** [neon-nyan/Collapse#107]
Hi! I'm a Korean who is a big fan of MiHoyo. This launcher is amazing! But unfortunately, it doesn't support Korean language. So the bottom line is that I want to help! Is there any way to help with Korean localization?

**Comment by bagusnl** [comment]
Hello! Thank you for giving interest in the project. 
ko-KR translation is already pulled to the repo as per #89, but it has seems to be accidentally removed from the Core files during the rebase. Will check on this
https://github.com/neon-nyan/Collapse/blob/1a4e0dea9765da234d7efb77b88f48dcc8d02f9d/Hi3Helper.Core/Hi3Helper.Core.csproj#L85-L107

**Comment by Cryotechnic** [comment]
Closing this issue, since the update was pushed to all users a couple of hours ago. Thanks for your report!
