### ISSUE TITLE
[Feature Request] Daily check-in Hoyolab in launcher

### ISSUE THREAD

**Issue by cupang-afk** [neon-nyan/Collapse#109]
i notices that you have built-in browser to view the web event and other update info

i think its a good idea if you also included same for daily check-in hoyolab that open in the built-in browser (in form of a button shortcut or something else)

![image](https://user-images.githubusercontent.com/66926348/233567559-10f5d554-cf64-4c98-8d67-7b279dbb674f.png)

**Comment by Tim-Paik** [comment]
I think this is a very good feature that can save players a lot of time

**Comment by Cryotechnic** [comment]
Heyo, assuming everything goes well, we plan on implementing this feature in the next major version of Collapse. Thanks for the suggestion!

**Comment by cupang-afk** [comment]
i do some dig down to their hoyolab site
and i found all daily login for all 3 games

i hope you guys also consider adding these

- [Honkai Impact 3rd](https://act.hoyolab.com/bbs/event/signin-bh3/index.html?act_id=e202110291205111)
- [Genshin Impact](https://act.hoyolab.com/ys/event/signin-sea-v3/index.html?act_id=e202102251931481)
- [Honkai: Star Rail](https://act.hoyolab.com/bbs/event/signin/hkrpg/index.html?act_id=e202303301540311)

**Comment by Cryotechnic** [comment]
Heyo! This feature has now been implemented and will ship as part of our next major Collapse version in the coming days. When that releases, I'm going to close this issue. Thank you for helping us improve Collapse!
