### ISSUE TITLE
[Preload Supported] Honkai: Star Rail[CN mainland Version] Support

### ISSUE THREAD

**Issue by fatinghenji** [neon-nyan/Collapse#110]
![image](https://user-images.githubusercontent.com/37131177/233837350-d56905f0-c9ac-4c7e-b2e0-358f08e018f9.png)
It looks like the current launcher only supports the global version and requests to add a China mainland version.

**Comment by Tim-Paik** [comment]
中国大陆：[启动器](https://autopatchcn.bhsr.com/client/cn/20230413215042_aplSx1uQpkRmXBCk/StarRail_setup_mys_20230422200015.exe) | [API](https://api-launcher-static.mihoyo.com/hkrpg_cn/mdk/launcher/api/resource?channel_id=1&key=6KcVuOkbcqjJomjZ&launcher_id=33&sub_channel_id=2) | [完整包](https://autopatchcn.bhsr.com/client/cn/20230413215209_VC9JD8S2WrcciZFu/StarRail_1.0.5.zip)
Global:  [Launcher](https://download-porter.hoyoverse.com/download-porter/2023/04/21/StarRail_setup_hoyoverse_20230422200015%20(2).exe) | [API](https://hkrpg-launcher-static.hoyoverse.com/hkrpg_global/mdk/launcher/api/resource?channel_id=1&key=vplOVX8Vn7cwG8yb&launcher_id=35&sub_channel_id=2) | [Full Client](https://autopatchos.starrails.com/client/download/20230413214947_toY0cWzqBhhM2EDV/StarRail_1.0.5.zip)

**Comment by fatinghenji** [comment]
> 中国大陆：[启动器](https://autopatchcn.bhsr.com/client/cn/20230413215042_aplSx1uQpkRmXBCk/StarRail_setup_mys_20230422200015.exe) | [API](https://api-launcher-static.mihoyo.com/hkrpg_cn/mdk/launcher/api/resource?channel_id=1&key=6KcVuOkbcqjJomjZ&launcher_id=33&sub_channel_id=2) | [完整包](https://autopatchcn.bhsr.com/client/cn/20230413215209_VC9JD8S2WrcciZFu/StarRail_1.0.5.zip) Global: [Launcher](https://download-porter.hoyoverse.com/download-porter/2023/04/21/StarRail_setup_hoyoverse_20230422200015%20(2).exe) | [API](https://hkrpg-launcher-static.hoyoverse.com/hkrpg_global/mdk/launcher/api/resource?channel_id=1&key=vplOVX8Vn7cwG8yb&launcher_id=35&sub_channel_id=2) | [Full Client](https://autopatchos.starrails.com/client/download/20230413214947_toY0cWzqBhhM2EDV/StarRail_1.0.5.zip)全局：启动器|API|完整客户端

How to use this?

**Comment by Tim-Paik** [comment]
> > 中国大陆：[启动器](https://autopatchcn.bhsr.com/client/cn/20230413215042_aplSx1uQpkRmXBCk/StarRail_setup_mys_20230422200015.exe) | [API](https://api-launcher-static.mihoyo.com/hkrpg_cn/mdk/launcher/api/resource?channel_id=1&key=6KcVuOkbcqjJomjZ&launcher_id=33&sub_channel_id=2) | [完整包](https://autopatchcn.bhsr.com/client/cn/20230413215209_VC9JD8S2WrcciZFu/StarRail_1.0.5.zip) Global: [Launcher](https://download-porter.hoyoverse.com/download-porter/2023/04/21/StarRail_setup_hoyoverse_20230422200015%20(2).exe) | [API](https://hkrpg-launcher-static.hoyoverse.com/hkrpg_global/mdk/launcher/api/resource?channel_id=1&key=vplOVX8Vn7cwG8yb&launcher_id=35&sub_channel_id=2) | [Full Client](https://autopatchos.starrails.com/client/download/20230413214947_toY0cWzqBhhM2EDV/StarRail_1.0.5.zip)全局：启动器|API|完整客户端
> 
> How to use this?

This is some information that may be useful to developers, but may not help you.

**Comment by bagusnl** [comment]
Thank you for the official launcher link, we will take a look at supporting CN region of HSR as well 
~~legit can't find the CN launcher link so thank you so much~~

**Comment by bagusnl** [comment]
@Tim-Paik Can you export the game folder tree for me? thank you

CMD cd to the folder containing game exe, do
`tree /A /F >HSR-CN.txt`

**Comment by Cryotechnic** [comment]
@fatinghenji Collapse has just been updated to 1.69.13 (Preview) which supports the CN version of HSR. If you would like to try it, please make sure that you are in the Preview branch. Stable should see the same update coming in the coming hours or days. Closing this for now as the original request has been fulfilled

**Comment by Tim-Paik** [comment]
> @Tim-Paik Can you export the game folder tree for me? thank you
> 
> CMD cd to the folder containing game exe, do `tree /A /F >HSR-CN.txt`

Sorry for the late reply, I've been sprinting for some exams recently.  Do you still need those directory listings?  I should be able to get the file list back to you within half a day if needed/no reply.

**Comment by bagusnl** [comment]
Hello @Tim-Paik !
As the HSR going to have an update tomorrow, I need some of your assistance.
Can you see if the LauncherResourceURL and GameDispatchURL (if possible) is updated and send them to me so we can update the launcher metadata? When you're ready you can send them to me either on Discord (`@bagusnl`) or by email bagusnl@protonmail.com

Thank you in advance! <3
