### ISSUE TITLE
[Feature Request] Option to disable game change warning

### ISSUE THREAD

**Issue by devrim6** [neon-nyan/Collapse#111]
Could you please add an option in the launcher settings that toggles the game chance warning on and off? Most of the time when I press the "Change" button I want to actually change the game, so I don't see the reason to have that confirmation window.

**Comment by Cryotechnic** [comment]
Hi, thanks for your feedback for Collapse! We're currently investigating whether this is possible to implement with our current app structure. Please keep in mind that games labelled as "Beta" by our launcher (e.g. Honkai: Star Rail), will most likely still ask you for a prompt. Furthermore, this may not be a change that will make it into our next mainline (1.70.X) version release, but rest assured that we're keeping this in mind as we develop Collapse.

**Comment by neon-nyan** [comment]
The initial implementation of this feature has been pushed and hopefully ready for the next stable release
