### ISSUE TITLE
Language Changes Tracking: ja-JP (Japanese) 

### ISSUE THREAD

**Issue by Vermilion-Sinsha** [neon-nyan/Collapse#113]
Hi! I am a Japanese Houkai&Genshin player and have been using this launcher for a week now.I like this Launcher very much!But unfortunately,current version does not officially support Japanese Language. Since Japanese has a similar grammar to Korean, I tried to support Japanese in my local environment by overwriting ko-KR.json file. Can you produce an official ja-JP.json file based on this translation?
[https://pastebin.com/4im0P8xm](url)
![スクリーンショット 2023-04-24 130505](https://user-images.githubusercontent.com/131636335/233899301-275676fe-1538-485c-8862-da32cf397520.png)
![スクリーンショット 2023-04-24 130625](https://user-images.githubusercontent.com/131636335/233899305-423f3260-3835-49cd-8101-32900ef02c66.png)
![スクリーンショット 2023-04-24 130539](https://user-images.githubusercontent.com/131636335/233899306-1ca3f39e-28d6-4fcd-95c5-8d5dacb3b506.png)

**Comment by neon-nyan** [comment]
Hi @Vermilion-Sinsha,
Thank you for your contribution for ja-JP localization.
Sure, we will add your localization to the repo. We will be moving to Crowdin for translation contribution.

**Comment by Vermilion-Sinsha** [comment]
Thanks for the move to Crowdin! However, there is one problem. Due to Japanese grammar, I need "Pg2Subtitle1_3" and "Pg2Subtitle2_5" for Japanese translation. But en-US.json does not have them. How can I add "Pg2Subtitle1_3" and "Pg2Subtitle2_5" in Crowdin? Sorry for asking such a rudimentary question as I am not familiar with development.

**Comment by neon-nyan** [comment]
Hi @Vermilion-Sinsha,
Sorry for my late reply. We already have ja-JP locale in Crowdin
https://crowdin.com/project/collapse-launcher/ja

The source in Crowdin should've been updated with the last changes
