### ISSUE TITLE
Language Addition Request (es-419, Español (Latinoamérica)

### ISSUE THREAD

**Issue by BloodDragooner2** [neon-nyan/Collapse#118]
Hi there, cool project! I'm interested in translating the strings of the launcher into Spanish, Latin America. Could anyone please guide me on where to start? I already have a Crowdin account!

Thank you!

**Comment by neon-nyan** [comment]
Hi @BloodDragooner2,
Thank you for your interest on this project.
We just added the language to Crowdin so you can start contributing there: https://crowdin.com/project/collapse-launcher/es-419
You can also join our Armada Discord (link is in the App Settings) to ease the communication with our team.

**Comment by BloodDragooner2** [comment]
Cheers, and thanks for the help!!
