### ISSUE TITLE
[Feature Request] Time played while using Collapse

### ISSUE THREAD

**Issue by gablm** [neon-nyan/Collapse#121]
A functionality I miss from other launchers is play-time tracking.
Given the large amount of time investment Hoyoverse games require in the long run, it would be great to know what is the total playtime of each game played thru Collapse.

(as HI3 and Genshin are quite old, there could be an option to add the playtime values you have from other "trackers" i.e. GOG Galaxy, Epic Games Store, Android and IOS app screen time)

**Comment by bagusnl** [comment]
I like the idea but for importing play time from other platforms seems quite complicated to do. What we can do instead is to manually input/edit play time themself

**Comment by gablm** [comment]
That's what I meant, sorry if my phrasing was not clear enough. The platforms were just a example of places where a player could manually get this information to insert it on collapse.

**Comment by Cryotechnic** [comment]
> I like the idea but for importing play time from other platforms seems quite complicated to do. What we can do instead is to manually input/edit play time themself

We could, but I know for a fact that GOG has an API for querying the total playtime, thru a GET request, and Epic probably has that as well. 

Leaving this here in case you're interested:

[Link 1](https://gist.github.com/Amrsatrio/20d2174583354ae4f0a24cf63764049f#file-libraryservice-java)
[Link 2](https://www.gog.com/forum/general/unofficial_gog_api_documentation)
