### ISSUE TITLE
Free space issues when resuming paused download

### ISSUE THREAD

**Issue by Falconozura** [neon-nyan/Collapse#122]
Hi ! So I'm having issues with resuming download. I already downloaded 40gb out of 60 gb in genshin. Suddenly my internet down and the download failed. Then i'm unable to continue the download due to not enough free space, Is there any solution to this? Thank you so much
![Screenshot 2023-04-28 194822](https://user-images.githubusercontent.com/57929995/235151797-801f28ce-e3b2-4254-8bde-f1ca074b6539.png)
![Screenshot 2023-04-28 194926](https://user-images.githubusercontent.com/57929995/235151946-a03b6bdc-2ad3-4754-bf65-8bd2e59eca03.png)

**Comment by neon-nyan** [comment]
Hi @Falconozura,

We are working on the hotfix for this issue
Hopefully, we can push the hotfix as soon as possible.

**Comment by neon-nyan** [comment]
We've just pushed a hotfix including a fix for this issue.
Please make sure you've updated your launcher to the latest one (1.69.15)
