### ISSUE TITLE
[Feature Request] Star Rail Graphic Settings

### ISSUE THREAD

**Issue by Slightlyxz** [neon-nyan/Collapse#123]
Not sure if I'm allowed to request features for Star Rail already

But I was wondering if you could add Quick Settings for Star Rail in which you can configure your graphic settings and possibly also enable 120fps.
There has been a couple standalone tools released the last few days, I have been using this one for example: https://github.com/NickTheHuy/HSR_FpsTool_GUI
Would be neat to have inside the settings for Star Rail. :)

**Comment by neon-nyan** [comment]
Hi @Slightlyxz,

Thank you for the suggestion.
We are currently working on this feature in this PR: #120 and to be expected to come in the next stable release (1.70.x)

**Comment by bagusnl** [comment]
# Feature Request Tracking
## Honkai: Star Rail - Game Settings
### Working tree
https://github.com/bagusnl/Collapse/tree/hsr-settings

### Backend
 - [ ] GameSettings Classes
	 - [x] BGMVolume
	 - [x] MasterVolume
	 - [x] Model (Graphics Settings)
		 - [ ] FPS (find a way to limit only 3 choices: 30, 60, 120)
		 - [ ] VSync
		 - [ ] RenderScale (double precision value, limit to only 5 options: 0.6, 0.8, 1.0, 1.2, 1.4)
		 - [ ] ResolutionQuality
		 - [x] ShadowQuality
		 - [x] LightQuality
		 - [x] ReflectionQuality
		 - [x] BloomQuality
		 - [x] AAMode (Anti-Aliasing)
	 - [x] PCResolution (Resolution and Fullscreen)
	 - [x] SFXVolume
	 - [x] VOVolume
	 - [ ] Context (waiting for all above to finish)
	 - [ ] Settings (waiting for all above to finish)

- [ ] UI (StarRailGameSettings.Ext.cs)
	- [ ] Graphics
		- [x] Resolutions + Fullscreen
		- [ ] FPS
		- [ ] VSync
		- [ ] Render Scale
		- [ ] Resolution Quality
		- [x] Shadow Quality
		- [x] Light Quality
		- [x] Reflection Quality
		- [x] Bloom Quality
		- [x] Anti Aliasing Mode
	- [ ] Audio
		- [ ] Main Volume
		- [ ] BGM Volume
		- [ ] SFX Volume
		- [ ] VO Volume
		
### Frontend
- [ ] UI  (StarRailGameSettings.xaml//xaml.cs)
 	- [ ] Graphics
		- [x] Resolutions + Fullscreen
		- [ ] FPS
		- [ ] VSync
		- [ ] Render Scale
		- [ ] Resolution Quality
		- [ ] Shadow Quality
		- [ ] Light Quality
		- [ ] Reflection Quality
		- [ ] Bloom Quality
		- [ ] Anti Aliasing Mode
	- [ ] Audio
		- [ ] Main Volume
		- [ ] BGM Volume
		- [ ] SFX Volume
		- [ ] VO Volume
		
- [ ] Localization
	- [ ] English
	- [ ] Notify everyone else on localization team

### Finalization
- [ ] Rebase
- [ ] Bug Checks
- [ ] PR

**Comment by Cryotechnic** [comment]
This feature will ship as part of our next mainline release. Please stay tuned in the coming days! Will close issue once version 1.70.X will drop.
