### ISSUE TITLE
Language Addition Request (de-DE, German (Deutsch) 

### ISSUE THREAD

**Issue by DasIschBims** [neon-nyan/Collapse#125]
Hey there, I already started to translate a portion of the json inside [my fork](https://github.com/DasIschBims/Collapse/).
I'll probably finish it in the next few days and open a PR.

## Contributor list (So far)
- @DasIschBims
- @kujou-kju

**Comment by neon-nyan** [comment]
Hi @DasIschBims,

Thank you for your contribution to this project.
Looking forward for the translation to complet and thank you for your work

**Comment by neon-nyan** [comment]
Hi @DasIschBims,
Sorry to disturb you a bit. Do you mind if we move to Crowdin to work on this localization? Since another person wanted to contribute in this localization as well.

**Comment by DasIschBims** [comment]
Sure thing, should we take the existing file from my fork?

**Comment by neon-nyan** [comment]
Just done importing the translation. Thank you~
https://crowdin.com/project/collapse-launcher/de

**Comment by DasIschBims** [comment]
Oh it's way easier with Crowdin 😂

The file is called ```en-us.json```, shouldn't it be ```de-de.json```?
![image](https://github.com/neon-nyan/Collapse/assets/46683337/f65889bd-e933-48e5-9a94-0228eb771e41)
