### ISSUE TITLE
Star Rail Player.log file not populating when launched via Collapse

### ISSUE THREAD

**Issue by Golumpa** [neon-nyan/Collapse#126]
I am unsure if this is a launcher issue or not however when launching the game via Collapse the `Player.log` file in the `%appdata%\..\LocalLow\Cognosphere\Star Rail\` directory is not being populated. The file is populated when running via the official launcher and via starting the StarRail.exe directly which gives me the reason to believe its the way the launcher is launching the game exe. Other files in the same directory are being populated such as the `output_log.txt`.

This file is being used by one of the only wish counters available currently to find the game directory.
https://gist.github.com/Star-Rail-Station/2512df54c4f35d399cc9abbde665e8f0

**Comment by bagusnl** [comment]
Cannot reproduce this issue on 1.69.15.0 (currently only available on Stable channel)
![image](https://user-images.githubusercontent.com/28079733/235514148-eab22e96-2a7a-4103-8129-df0dc8e23603.png)
both files were deleted prior to launching with Collapse

Can you send Collapse log when its starting a game?

**Comment by Golumpa** [comment]
Yes it seems to only populate the file when show console is turned on in the launcher settings.
When the console is not shown the file does not seem to populate for me.

Console log doesn't show anything useful, but here it is.
<details>
  <summary>Console Log</summary>
  
  There is more but its trimmed down to save space, the continued part is just normal stuff that I get when I launch normally.
  
  ```javascript
  [Schm]  Running Collapse Launcher [1.69.15], [Stable], under Windows 11 (build: 22621.0), as jonat
[Schm]  Runtime: .NET 7.0.2 - WindowsAppSDK 1.3
[Schm]  Locale file: en-us.json loaded as English by neon-nyan, CryoTechnic
[Schm]  Locale file: id-id.json loaded as Bahasa Indonesia by neon-nyan
[Schm]  Locale file: ko-kr.json loaded as 한국어 by despenser08
[Schm]  Locale file: pt-pt.json loaded as Português (Portugal) by gablm
[Schm]  Locale file: vi-vn.json loaded as Tiếng Việt by kleqing
[Schm]  Locale file: zh-cn.json loaded as 简体中文 by misaka10843
[Info]  Discord Presence DLL: C:\Program Files\Collapse Launcher\app-1.69.15\Lib\discord_game_sdk.dll doesn't exist! The Discord presence feature could not be used.
[Info]  Welcome to Collapse Launcher v1.69.15 - Windows 11 (build: 22621.0)
[Info]  Application Data Location:
        C:\Users\jonat\AppData\LocalLow\CollapseLauncher
[Info]  Getting CDN Content from: GitHub at URL: https://github.com/neon-nyan/CollapseLauncher-ReleaseRepo/raw/main/notification_stable.json
[Info]  Getting CDN Content from: GitHub at URL: https://github.com/neon-nyan/CollapseLauncher-ReleaseRepo/raw/main/squirrel/stable/RELEASES?arch=x64&os=windows
[Schm]  Initializing Honkai: Star Rail - Global...
[Schm]  Initializing Region Honkai: Star Rail (Global) Done!
[Info]  Getting CDN Content from: GitHub at URL: https://github.com/neon-nyan/CollapseLauncher-ReleaseRepo/raw/main/stable/fileindex.json
[Info]  Getting CDN Content from: GitHub at URL: https://github.com/neon-nyan/CollapseLauncher-ReleaseRepo/raw/main/metadata/metadatav2_stablestamp.json
[Schm]  Page changed to App Settings
[Schm]  Page changed to Launcher
[Info]  Running game with parameters:

[Warn]  ================================================ GAME STARTED ================================================
[Game]  Loading player data from C:/Program Files/Star Rail/Games/StarRail_Data/data.unity3d
[Game]  Initialize engine version: 2019.4.34f1 (e38ae60407)
[Game]  [Subsystems] Discovering subsystems at path C:/Program Files/Star Rail/Games/StarRail_Data/UnitySubsystems
[Game]  GfxDevice: creating device client; threaded=1
[Game]  Direct3D:
[Game]      Version:  Direct3D 11.0 [level 11.1]
[Game]      Renderer: NVIDIA GeForce RTX 3060 Laptop GPU (ID=0x2520)
[Game]      Vendor:
[Game]      VRAM:     6009 MB
[Game]      Driver:   31.0.15.3141
[Game]  WARNING: Shader Unsupported: 'Unlit/GLESDummyDepth' - All passes removed
[Game]  WARNING: Shader Did you use #pragma only_renderers and omit this platform?
[Game]  ERROR: Shader Unlit/GLESDummyDepth shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[Game]  <RI> Initializing input.
[Game]
[Game]  <RI> Input initialized.
[Game]
[Game]  <RI> Initialized touch support.
[Game]
[Game]  UnloadTime: 0.647400 ms
[Game]  InControl (version 1.8.8 build 9375)
[Game]  UnityEngine.Logger:Log(LogType, Object)
[Game]  UnityEngine.Debug:Log(Object)
[Game]  System.Action`1:Invoke(T)
[Game]  InControl.InControlManager:OnEnable()
[Game]
[Game]  (Filename: D:\RPGEngine\EngineWindowsBuildEngine\rpg_engine\Runtime/Export/Debug/Debug.bindings.h Line: 39)
[Game]
[Game]  WwiseUnity: Wwise(R) SDK Version 2019.2.14 Build 7616.
[Game]  UnityEngine.Logger:LogFormat(LogType, String, Object[])
[Game]  UnityEngine.Debug:LogFormat(String, Object[])
[Game]  AkWwiseInitializationSettings:InitializeSoundEngine()
[Game]  AkInitializer:OnEnable()
[Game]
[Game]  (Filename: D:\RPGEngine\EngineWindowsBuildEngine\rpg_engine\Runtime/Export/Debug/Debug.bindings.h Line: 39)
[Game]
[Game]  WwiseUnity: Setting Plugin DLL path to: C:/Program Files/Star Rail/Games/StarRail_Data\Plugins\x86_64
[Game]  UnityEngine.Logger:Log(LogType, Object)
[Game]  UnityEngine.Debug:Log(Object)
[Game]  AkCommonPlatformSettings:get_AkInitializationSettings()
[Game]  AkWwiseInitializationSettings:InitializeSoundEngine()
[Game]  AkInitializer:OnEnable()
[Game]
[Game]  (Filename: D:\RPGEngine\EngineWindowsBuildEngine\rpg_engine\Runtime/Export/Debug/Debug.bindings.h Line: 39)
[Game]
[Game]  WwiseUnity: Sound engine initialized successfully.
[Game]  UnityEngine.Logger:Log(LogType, Object)
[Game]  UnityEngine.Debug:Log(Object)
[Game]  AkWwiseInitializationSettings:InitializeSoundEngine()
[Game]  AkInitializer:OnEnable()
[Game]
[Game]  (Filename: D:\RPGEngine\EngineWindowsBuildEngine\rpg_engine\Runtime/Export/Debug/Debug.bindings.h Line: 39)

.......
  ```
  
</details>

**Comment by bagusnl** [comment]
# Cause found
`-nolog` parameter is appended to launch option when Collapse console is disabled.

### Source:
https://github.com/neon-nyan/Collapse/blob/6b371b48737a8517cb56d2be0d1bbb1c2281a6f5/CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs#L705-L706
Removing that logic fixed the behavior of log not being generated when Collapse console is disabled

### Other (potential) problem
Removing that logic will still append game logs to Collapse log, even when console is disabled, which IMO is fine.

## Current workaround
Enable Console in Collapse Settings.

## Planned bug fix release
1.70.0

**Comment by Golumpa** [comment]
Late to the party... Is it me or is '-nolog' still appended to the executable when the console is not enabled? As the Player.log file is still not populating.

This is from the latest preview build:
https://github.com/neon-nyan/Collapse/blob/c82ccfcf2fbd671e6fdd6c680eabcfe3163c46b8/CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs#L706-L707

**Comment by gablm** [comment]
I checked and my player.log is also not populating, although it think it did work for a while when @bagusnl came up with a fix for the issue.

Removing those two lines seems to indeed solve the issue.

**Comment by bagusnl** [comment]
I was legit not aware that there were 2 of the same thing, and how did it worked as early as last time I tested it was 1.70.4 ???
But thank you for noticing it, we'll wait for neon/cry0 to merge this and fix said issue. Sorry for my dumbass brain not re-checking it again.
