### ISSUE TITLE
Hiding "Change" button on the top

### ISSUE THREAD

**Issue by cabera2** [neon-nyan/Collapse#127]
I afraid I'm the only one thinking this but,
I think that "Change" button and the warning dialogue(about changing region) doesn't necessary.
I wish the launcher switch the game immediately when I click the game title from the list.

Or, if other ones are thinking that button is necessary, then how about add a "quick switch" option in setting and let us hide the "change" button by toggleing that option?

This is my first time summiting issue here so please let me know if I did something wrong.

**Comment by bagusnl** [comment]
Hello, thank you for giving your thoughts on this project :D
1. The `Change` warning dialog is already addressed over at #111 and should be released on the next major release of Collapse (1.70.0)
2. For the quick switch function, we'll talk about it

Thanks again for trying out Collapse, hope you're having a great time o/

**Comment by cabera2** [comment]
Thank you!
