### ISSUE TITLE
[Bug] Draggable area of ​title bar covers the minimize button

### ISSUE THREAD

**Issue by Scighost** [neon-nyan/Collapse#137]
In StartUpPage or UpdatePage, the draggable area will be changed by call `ChangeTitleDragArea.Change(DragAreaTemplate.Full)`. But there is a problem with the `Full`, which makes the area cover the minimize button.

https://github.com/neon-nyan/Collapse/blob/4255da8977638bde00629a10814cb69afa7017cd/CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs#L51-L60

It should be modified to the following:

``` diff
private RectInt32[] DragAreaMode_Full
{
    get => new RectInt32[1]
    {
        new RectInt32(0,
            0,
-           (int)(m_windowPosSize.Width * m_appDPIScale),
+           (int)((m_windowPosSize.Width - 96) * m_appDPIScale),
-           (int)(40 * m_appDPIScale))
+           (int)(48 * m_appDPIScale))
    };
}
```

Video:

https://github.com/neon-nyan/Collapse/assets/61003590/0f1efb34-af18-4dc8-a7ef-6c4cb161a99d

**Comment by Cryotechnic** [comment]
Heyo, thanks for your interest in Collapse! Going to close this as your fix has been merged into main and the next preview build should permanently resolve this issue.

Thanks again!
