### ISSUE TITLE
Language Changes Tracking: zh-CN (简体中文 - Simplified Chinese)

### ISSUE THREAD

**Issue by neon-nyan** [neon-nyan/Collapse#14]
This issue is supposed to provide updates for the language content continuously.
The changes will be updated in every changes of the main language (en - English) so the changes can be openly contributed.

## Contributor list (So far)
* @misaka10843

**Comment by neon-nyan** [comment]
**Hi @misaka10843,**

Sorry to bother you,
We have some parts need to be translated for ``zh-CN`` translation. Can you update the translation for the section above?

**Comment by misaka10843** [comment]
> **Hi @misaka10843,**
> 
> Sorry to bother you, We have some section need to be translated for `zh-CN` translation. Can you update the translation for the section above?

Of course, I will update the translation in the next few days

**Comment by neon-nyan** [comment]
Hi @misaka10843,

Sorry to bother you on this.
I've just added some strings that need to be translated (as you can see above).
Can you update the translation for the strings mentioned above?

**Comment by Cryotechnic** [comment]
@misaka10843 Hai hai o/

With Collapse 1.69.0 launching very soon, I was wondering if it was possible for you to go through all the zn-CN strings and make sure that they are up-to-date with the en-US ones? Thanks again for all your work!

**Comment by neon-nyan** [comment]
Hi @misaka10843 
To give you more detail what things have been changed, you can take a look the details here:
https://github.com/neon-nyan/Collapse/blame/b68f9ee8605d7f4c7ab9f874b378d2d990e072ff/Hi3Helper.Core/Lang/en.json

**Comment by misaka10843** [comment]
> @misaka10843海海 o/
> 
> 随着 Collapse 1.69.0 即将推出，我想知道您是否可以浏览所有 zn-CN 字符串并确保它们与 en-US 字符串保持同步？再次感谢您的所有工作！



> 嗨@misaka10843 为了更详细地为您提供更改的内容，您可以在此处查看详细信息：https://github.com/neon-nyan/Collapse/blame/b68f9ee8605d7f4c7ab9f874b378d2d990e072ff/Hi3Helper.Core/Lang/en.json

Ok, I will translate soon. Thanks for reminding me

**Comment by bagusnl** [comment]
Heyyo @misaka10843 
We have moved the language tracking to use Crowdin instead over at https://crowdin.com/project/collapse-launcher Consider joining the project to get notified about any changes that we made regarding translation.
Currently zh-CN translation is quite a bit behind by about 40-ish strings that needs to be translated. Let us know if you have any issue regarding the translation process.

Thank you in advance for your work ❤️

**Comment by misaka10843** [comment]
> Heyyo @misaka10843 We have moved the language tracking to use Crowdin instead over at https://crowdin.com/project/collapse-launcher Consider joining the project to get notified about any changes that we made regarding translation. Currently zh-CN translation is quite a bit behind by about 40-ish strings that needs to be translated. Let us know if you have any issue regarding the translation process.
> 
> Thank you in advance for your work ❤️

Ok, but since I didn't see it in time, I have submitted a translation from my branch, and I will submit it directly from crowdin after that, thanks for reminding me o((>ω< ))o

**Comment by imgradeone** [comment]
hi i'm coming to Crowdin to contribute to Collapse

**Comment by imgradeone** [comment]
also I noticed #135

**Comment by imgradeone** [comment]
@neon-nyan I need to use `_StartupPage.Pg2Subtitle1_3` key to fine-tune the translation, but Crowdin didn't provide this slot
