### ISSUE TITLE
No "Cache Update" and "Game Settings" on Genshin

### ISSUE THREAD

**Issue by tilsgee** [neon-nyan/Collapse#140]
Hi. Consider this as minor bug

both Honkai have "Cache Update" and "Game Settings"

![gambar](https://github.com/neon-nyan/Collapse/assets/62179071/37995969-68cf-40a9-983e-f4aea86fcba8)
![gambar](https://github.com/neon-nyan/Collapse/assets/62179071/9878ac43-7666-48d3-97ea-ab7c31013e5d)

that doesn't apply to Genshin

![gambar](https://github.com/neon-nyan/Collapse/assets/62179071/9b986a46-20ec-453e-b8d6-c36777d21bc8)

Why?

**Comment by tilsgee** [comment]
> Hello, this is actually not a bug and just caused by how Genshin manages its caches data compared to Honkai. Rest assured, when you press "Repair Game" in Genshin using Collapse, your Genshin's "Caches" will be checked and updated too.
> 
> And because of neon's work in the repair mechanism, even a Full Check, which checks every file checksum only takes a few minutes on my SATA SSD. Though, most of the time, a Quick Check would do just fine as well, and it instantly checks every file in seconds because it only checks if the file exists and if the size match with the database.

ahh.. that's answered "Cache Update" thing. how about "Game Settings" part?

**Comment by bagusnl** [comment]
We haven't implemented a Game Setting page for Genshin yet due to how Genshin implements their game settings, it's an absolute mess. If you or someone have the motivation and knowledge to do it, we are pleased to accept the help on Genshin Game Settings part!

**Comment by bagusnl** [comment]
Just a heads up, currently we are working on the implementation for Genshin's GameSettings with @Myp3a (thanks Myp3a for all the work ❤️), its targeted to be released somewhere after Preview branch after 1.70.x Release branch is finalized so its not too chaotic.

Working branch for this feature is on my fork https://github.com/bagusnl/Collapse/tree/gi-settings

Most of the progress are tracked on Discord and proper PR will be made once everything is ready and tested against main dev branch.
