### ISSUE TITLE
Game uninstallation also deletes unrelated files in the folder

### ISSUE THREAD

**Issue by Rin3105** [neon-nyan/Collapse#141]
### System Information
* CPU: i7-10750H
* RAM: 16GB DDR4 2933MHz
* Windows version and build number: Windows 10 Pro version 22H2, build number 19045.2965
* Collapse Version: 1.70.4 Preview

### Prerequisites
* On latest Collapse Launcher version? Yes
* Error message appears in console/log? No
* No issue created in repository? No issue
* Reproduceable bug? Yes

### Bug Description
[ Describe the bug found in Collapse ] The uninstallation of any games with Collapse Launcher also deletes other unrelated files within the game folder.

### Steps to Reproduce Bug
1. [ First step ] Install the game into any desired locations on your PC.
2. [ Second step ] Put in some random files that do not belong to the game into the game folder.
3. [ Third step ] Choose "Uninstall Game" in the launcher's Quick Settings menu.
4. [ Fourth step ] The folder is empty, with only the "config.ini" file remained, and no traces of the random files you put in before.
***Expected behavior:***
[ Describe what you expected to happen ] The launcher would only remove files that belong to the game, and keep the unrelated files in the folder.
***Actual behavior:***
[ Describe what happened ] The launcher removed everything, including the unrelated files in the game folder, and could not be found in Recycle Bin.

### Console log
[ Paste the log inside a code block here or attach the log file here ] 
[Log-2023-06-01.log](https://github.com/neon-nyan/Collapse/files/11620905/Log-2023-06-01.log)
[ Default location for the log file is `C:\Users\%username%\AppData\LocalLow\CollapseLauncher\GameFolder\_logs` ]
### Screenshot
[ Attach a screenshot if applicable ]
![Screenshot 2023-06-01 111044](https://github.com/neon-nyan/Collapse/assets/52498640/23810862-176c-4bac-8e92-d51571b56514)
Three random text files in "Honkai Star Rail" folder, meant for reproducing this issue.

![Screenshot 2023-06-01 111847](https://github.com/neon-nyan/Collapse/assets/52498640/cd9cb45f-f1a8-4fd8-9cbb-d4ba529cd7a0)
The "Honkai Star Rail" folder after game uninstallation, with no traces of the three random text files.

**Comment by bagusnl** [comment]
Issue updated
Notes: https://canary.discord.com/channels/734618289115758592/880454043028324362/1109357324935643176
CC @neon-nyan

**Comment by Rin3105** [comment]
Hi neon-nyan,

First of all, I would like to say that I totally understand about the situation that you and the team have been going through. It's no easy to deal with job urgency and other stuff to do in real life.

Anyway, from what you were saying that re-indexing the game files in each update of the game is prone to be useless, since other unrelated files will be potentially indexed, I have a few points to ask:
1. Would that be meaning it's no point to add such behavior to the launcher for all other Hoyoverse games that don't come with `pkg_version` file like Honkai does? 
2. From what you mentioned about re-indexing unrelated files, does it also happen with Honkai game with their `pkg_version` file? Or they have already set their own special reference that the launcher can use to tell exactly which file to delete, per each game update? 
3. Is the solution you mentioned the only best solution that we have for now? 

I'm looking forward to hear from your response soon. Thank you so much.

**Comment by bagusnl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New Game Uninstall method](https://trello.com/c/1LRIr4IH/16-new-game-uninstall-method)
