### ISSUE TITLE
Optimize the display of NavigationView

### ISSUE THREAD

**Issue by Scighost** [neon-nyan/Collapse#143]
`NavigationView` in `MainPage` shows with `PaneDisplayMode="LeftMinimal"`, but when the left panel is expanded, the outer border of the panel and the NaviationView have 1 pixel blank area. If the contrast between the background image and the color of the application theme is obvious, then this one pixel blank area will be displayed as the color of the background image.

The reason is that in the default style of `NavigationView`, the `BorderThickness` of `SplitView` is set to 1, but the `BorderThickness` in default style of `SplitView` only affects the pane element, but not the content element. So the left pane of `NavigationView` always has 1 margin relative to the content.

Maybe my description is not very clear, see the video below for the specific.

### Source Style

https://github.com/microsoft/microsoft-ui-xaml/blob/4cbade6959cda4fca42a299fb540adc2f99c1e8a/dev/NavigationView/NavigationView.xaml#L460-L465

https://github.com/microsoft/microsoft-ui-xaml/blob/4cbade6959cda4fca42a299fb540adc2f99c1e8a/dev/NavigationView/NavigationView_rs1_themeresources.xaml#L278

https://github.com/microsoft/microsoft-ui-xaml/blob/4cbade6959cda4fca42a299fb540adc2f99c1e8a/dev/SplitView/SplitView_themeresources.xaml#L594-L631

### How to do

Add resource in MainPage

``` xml
<Page.Resources>
    <Thickness x:Key="NavigationViewBorderThickness">0</Thickness>
</Page.Resources>
```

### Before and After Comparison

Please note the window border.

https://github.com/neon-nyan/Collapse/assets/61003590/513aa4af-32a9-417b-b66a-9c60e402c0bb

**Comment by neon-nyan** [comment]
Hi @Scighost,

Thank you for the suggestion and your contribution on this project (Also sorry that I was on break working on this project)
As per latest PR being merged, we can close this issue now.
