### ISSUE TITLE
Close "Language Changes Tracking" issues

### ISSUE THREAD

**Issue by gablm** [neon-nyan/Collapse#145]
Currently, there are various language issues opened because of how localization used to be done.
It is a bit redundant to keep them open when the localization is now done on [Crowdin](https://crowdin.com/project/collapse-launcher).

My suggestion is to close them and open a general pinned issue called something like "Localization Changes" where there would be a link to Crowdin and posts when new strings are added to crowdin. That way, localizers could subscribe to the issue and get notified when new strings are added if they want to do so.

**Comment by Cryotechnic** [comment]
Good idea, thanks for the suggestion!
