### ISSUE TITLE
launcher's locate game logic could be optimized.

### ISSUE THREAD

**Issue by unknown10777** [neon-nyan/Collapse#150]
1) Personally, when user opened the page, it should automaticlly locate the game rather than showing "Install Game" button, this is confusing.
2) The "locate directory" function didn't find the game when user downloads a full zip but **not installed the official launcher** from official before, it should be "locate executable file" instead.
![image](https://github.com/neon-nyan/Collapse/assets/83267603/b344fbde-75dc-4145-8f57-c017464438e7)
![image](https://github.com/neon-nyan/Collapse/assets/83267603/1497d67d-b430-488d-811e-ea9fdc751cf2)

**Comment by bagusnl** [comment]
Hi~ Thanks for the suggestion regarding UI/UX for Collapse! Yes, I do agree that these are quite confusing for new user. For that:
1. We can change the localization to instead use the words "Install/Locate Game" as a temporary fix until better fix is found.
> Maybe when the region is initialized, if current Collapse configuration doesn't have a valid game installation directory we immediately grabs it from official launcher configs instead of waiting for user input (clicking the Install Game button)

2. Once the full zip is downloaded, Collapse should be able to detect it and then do the installation procedure
> Collapse currently cannot resume incomplete download from official launcher due to difference in downloading scheme.
> This issue might also related to #122
