### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by KayadeUwU** [neon-nyan/Collapse#155]
![image](https://github.com/neon-nyan/Collapse/assets/100220752/dc75e9aa-d0d2-4be2-a703-3a095cb5b634)
Instantly crash when opened. Retried many times but no results.

**Comment by bagusnl** [comment]
Hi, I noticed your Collapse has been launched with an argument of `--load-extension=...`
Make sure the shortcut you use to run Collapse doesn't have any launch arguments embedded in it.

**Comment by Cryotechnic** [comment]
Closing as issue is stale and no new information has been provided. Feel free to re-open if you have anything to add!
