### ISSUE TITLE
Can't download Honkai Impact 3rd, crashes

### ISSUE THREAD

**Issue by Walkar66** [neon-nyan/Collapse#156]
![image](https://github.com/neon-nyan/Collapse/assets/63099104/980c4bba-e2f7-439d-a3c7-3b3267ab2ae4)

**Comment by bagusnl** [comment]
similar issue #154 
the commit is ready, waiting for fix release

**Comment by bagusnl** [comment]
Hi, I've made a debug build you can test here:
https://www.mediafire.com/file/13h54rtrckdkmbe/Collapse-Debug_670b93d47783e2b409bdb2bf7bed2345fbd0c949_10.0.19041.0_Net7.0.7z/file
Please keep in mind that this debug build doesn't have any updater so make sure to use normal builds (pre/stable) after you've done with downloading the game. 

To use this build, just extract it and run CollapseLauncher.exe, all configs from normal build will be used.

Let us know if you have any difficulties or issues using this build.

**Comment by neon-nyan** [comment]
We are currently working on the fix for this bug and hopefully, the hotfix will be shipped soon.

**Comment by neon-nyan** [comment]
Hi @Walkar66,

This issue should've been fixed in the recent update. Please ensure that your launcher has the latest update.
