### ISSUE TITLE
Add Traditional Chinese on crowdin

### ISSUE THREAD

**Issue by seriaati** [neon-nyan/Collapse#160]
I would like to translate for traditional chinese.

**Comment by neon-nyan** [comment]
Hi @seriaati,

Thank you for your interest on the localization contribution.
We will be adding the Traditional Chinese translation option and we will let you know once we have added it into Crowdin.

**Comment by Cryotechnic** [comment]
Heyo @seriaati, closing this issue now as all localization additions and requests are done in #146. We've added Traditional Chinese to the list of localizable languages, so feel free to contribute. Thanks again for all your work!
