### ISSUE TITLE
Collapse Launcher update issue in China

### ISSUE THREAD

**Issue by Dinnerbonex3rd** [neon-nyan/Collapse#169]
![image](https://github.com/neon-nyan/Collapse/assets/121348180/310d3745-7c0f-4c78-9992-436656cf7fe9)
I can‘t update this launcher in China as the pic shows normally.

**Comment by neon-nyan** [comment]
Hi @Dinnerbonex3rd,

Have you tried to change the Repository CDN to something else like Statically and jsDelivr?
<img width="316" alt="image" src="https://github.com/neon-nyan/Collapse/assets/30566970/b052e559-873e-44bc-adb6-7638b67a6569">

**Comment by Dinnerbonex3rd** [comment]
solved,I turned to jsDelivr,and It worked.thx

**Comment by Cryotechnic** [comment]
Closing as issue is fixed.
