### ISSUE TITLE
[Enhancement] Merging file slices is unnecessary

### ISSUE THREAD

**Issue by Scighost** [neon-nyan/Collapse#174]
Hi!

Now the steps to install game are `Download, Merge, Verify and Unzip`, where the merge operation not only wastes time, but also causes additional disk writes.  And this can be avoided.

All that is needed is a stream wrapper that internally maintains references to each file slice stream, and then read data from different file streams based on current position.

I’ve already implemented in [my project](https://github.com/Scighost/Starward), proving that the idea does work. You can refer to my code:
https://github.com/Scighost/Starward/blob/af9b6b1a2f3f2d3ead8c51adfd6d1cea78440e32/Starward/Services/DownloadGameService.cs#L1334

I recorded a video to demonstrate this feature (10x speed):

https://github.com/neon-nyan/Collapse/assets/61003590/a87e37e9-f11e-4b95-869f-a09f158f9681

**Comment by Scighost** [comment]
Because I am not familiar with the structure of Collapse, I cannot make pull request.

**Comment by muscularcandy67** [comment]
I am actually interested in your download solution, I assume with that window you can download/update game without staying on the game page, therefore starting another game or changing settings or everything else as long as it has nothing to do with the game currently being in any install phase

**Comment by neon-nyan** [comment]
Hi @Scighost,

Thank you for the suggestion. We actually already made the implementation of the stream wrapper and use what is called as ``CombinedStream`` here:
https://github.com/neon-nyan/Hi3Helper.EncTool/blob/16af1c15211ead555dd1f303def5e2cf4db9b7cf/Streams/CombinedStream.cs

This has been partially implemented in Genshin installation but we might implement this improvement for others in the future release.

**Comment by Scighost** [comment]
@neon-nyan 

Oh, I didn't noticed that you did implemented the combined stream.

However, file slices of each segments are still be merged into one file when install Genshin. Please don't forget to optimize it.

![image](https://github.com/neon-nyan/Collapse/assets/61003590/53751e9f-72a5-4cd4-a055-b91c3f8cede2)

![image](https://github.com/neon-nyan/Collapse/assets/61003590/fd2172c3-dccf-4fdb-9926-1ba05db8063d)

**Comment by Cryotechnic** [comment]
> @muscularcandy67
> 
> I just start a standalone process for downloading.

Could be interesting to consider implementing this for #44

**Comment by muscularcandy67** [comment]
> > @muscularcandy67
> > I just start a standalone process for downloading.
> 
> Could be interesting to consider implementing this for #44

Yup, that's why I was curious about it

**Comment by bagusnl** [comment]
### Unrelated
@Scighost can you read my Discord DM, sorry to bother!

**Comment by Scighost** [comment]
> ### Unrelated
> @Scighost can you read my Discord DM, sorry to bother!

### Also Unrelated

Have done.

**Comment by Scighost** [comment]
Closed for feature implemented.
