### ISSUE TITLE
Not really an issue, but also an issue

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/Collapse#18]
When clicking on Discord in your Launcher, the invite is invalid. You probably lost boosts and the custom invite link went poof. Also I'm curious when you are gonna release the next version. I saw in the commits there is an instant region loading update and I want to try it out.

**Comment by neon-nyan** [comment]
Hi there,
Yes, I just noticed that the Discord Server link is expiring and it was a link to our Armada Discord Server, Ironmaiden. We will change the link to the old one.

For the new "Instant Region Loading" commit, it will be coming to the next preview build later. For your information, the loading time isn't really instant, It's just getting faster at some parts like background image and accent color loading. For launcher API loading, it depends on your internet connection.

But if you really want to try out, you can just wait for the next preview release to come out or you can build the app for yourself :smiley:

**Comment by muscularcandy67** [comment]
That's what I actually did yesterday after the post, and it's still a bit faster than than the release. 
On another note, if you're open to suggestions, I have a few in mind, if not you can just ignore the rest of this post.
Suggestion list:
1. I think the extra confirmation for changing region/game is redundant. We already have to click on the dropdown menu, select the region/game, and then click change. 
2. This is probably harder to code, more like it requires some time. When Zeenless Zone Zero drops and when Honkai Star Rail drops the amount of stuff in the dropdown menu is going to be a lot. So instead of having the dropdown menu, having icons for HI3, GI, ZZZ, HSR where the dropdown and the change button are. So when I select HI3, it opens HI3 downloaded region first, but in a menu right under the icons, I can select the region. If this is hard to understand I can generate an image of what I mean, which of course would be just to visualize what I mean, and not how it will end up looking eventually.
3. Having the option to have the launcher start with Windows.
4. Having a tray icon, like official launcher have
5. Having the option to select the behavior of close button with the tray icon update: either minimizing the launcher to system tray or closing the launcher

**Comment by neon-nyan** [comment]
Hi @muscularcandy67,

About the first suggestion. Actually, I've previously made a plan about this to be just one click. But since the confirmation has a functionality to inform the users that they will enter another Game Region/Server, so the users will not accidentally switched to another region/server and then download it. But I will keep this suggestion in-mind.

For the second suggestion. Yes, I will be planning to make the region drop-down as per-category based to make navigation easier and less confusing. I think I'll make this happen once Honkai: Star Rail come out. But of course, There will be a lot of code refactoring for this. Still, I'll make this as a plan in the future.

For the 3rd - 5th suggestions, I'm not sure if I'll be able to do that (at least for now). Since I'm using WinUI 3/WindowsAppSDK 1.1 to make this launcher and It has some limitation with Win32 API Calls/Functionalities (IIRC). Like having a system tray and changing Windows Environment for setting up the auto start-up sequence.

Anyway, thank you for the suggestions! 😄

**Comment by muscularcandy67** [comment]
Yet another enhancement suggestion, Genshin launcher recently added the ability to quickly go to your screenshot folder, I think it would be a pretty nice addition to also have that in Collapse Launcher for all games (yes talking for the future too for ZZZ and HSR),

**Comment by muscularcandy67** [comment]
The next one is just a little perk, and I don't know if it will be feasible or not, and it only came to mind now that Genshin is under maintenance. When the maintenance is up, the launcher will show that the game is in maintenance and how much time remains or when it will end based on the timezone that's currently on PC. If it's not feasible just discard this idea, as I said it would be just a really small QoL feature, nothing that someone can't check by loading the game for a few second anyway

**Comment by Cryotechnic** [comment]
> The next one is just a little perk, and I don't know if it will be feasible or not, and it only came to mind now that Genshin is under maintenance. When the maintenance is up, the launcher will show that the game is in maintenance and how much time remains or when it will end based on the timezone that's currently on PC. If it's not feasible just discard this idea, as I said it would be just a really small QoL feature, nothing that someone can't check by loading the game for a few second anyway

There are a couple of ways to do this, the first one being to manually hardcode maintenance dates in a file somewhere once we know them. The second option would be to figure out if there is a public-facing URL that GI/HI3 query to find out if there is a maintenance in progress (similar to what [FFXIV](https://frontier.ffxiv.com/worldStatus/gate_status.json?lang=en-us) uses. I've been trying to find it but have yet to be successful, maybe someone else will have more luck?

**Comment by muscularcandy67** [comment]
I think it's a request made in game. When there is a maintenance you can still load the game, but as soon as you try to login it prompts you that the game is in maintenance. Therefore I think it depends on the server response, though I don't know if you need to be logged in in order to reach that server and then get that respone or simply quering it and check if it gives the maintenance flag would work even without being logged in

**Comment by Cryotechnic** [comment]
> I think it's a request made in game. When there is a maintenance you can still load the game, but as soon as you try to login it prompts you that the game is in maintenance. Therefore I think it depends on the server response, though I don't know if you need to be logged in in order to reach that server and then get that respone or simply quering it and check if it gives the maintenance flag would work even without being logged in

Did some digging through Wireshark, but couldn't find the URL that the launcher uses to check if there is still maintenance ongoing. Maybe it is a specific response type, but I am unsure how you would filter that through Wireshark. Maybe someone else knows how to?

**Comment by Cryotechnic** [comment]
Closing this since the tracking issues have been merged into #79
