### ISSUE TITLE
[Bug]: Pause button is covered during pre-download on small window size

### ISSUE THREAD

**Issue by monsterxcn** [neon-nyan/Collapse#191]
### Affected Version

Collapse 1.70.11

### Bug Behavior

![image](https://github.com/neon-nyan/Collapse/assets/22407052/cc96882c-f35f-4f8f-8531-322bf27b96e6)

When I switch to the normal window size everything shows up just fine.

### Expected Behavior

Just show up completely on small window size.

### Steps to reproduce

1. Switch to small window size
2. Start Genshin Impact pre-download

**Comment by riwama** [comment]
i have the same problem here
![image](https://github.com/neon-nyan/Collapse/assets/69742932/aed4d2ad-9e25-4caf-a826-78bab2f02c54)

**Comment by bagusnl** [comment]
Hello, sorry for taking a bit to respond 

Thank you for reporting the issue, we will look into it!

**Comment by Cryotechnic** [comment]
FYI, a fix will ship as part of the 1.71.3 hotfix. Closing issue, but feel free to reopen if the issue persists after the update.
