### ISSUE TITLE
[BUG] [Tracking] Honkai: Star Rail Game Repair/Cache Update Issue

### ISSUE THREAD

**Issue by bagusnl** [neon-nyan/Collapse#206]
We are aware of a bug in Game Repair and Cache Update mechanism due to changes on miYoYo side. @neon-nyan is working on a fix and we'll use this for tracking said issue.

**Comment by neon-nyan** [comment]
The issue should've been fixed in the latest commit.
Keep in mind that the feature would still be disabled until we ship the fix to both preview and stable releases.

**Comment by Cryotechnic** [comment]
Closing as issue is now resolved
