### ISSUE TITLE
[Request]Borderless Fullscreen Support

### ISSUE THREAD

**Issue by cabera2** [neon-nyan/Collapse#224]
Starrail supports borderless fullscreen but genshin and 3rd doesn't
I don't know this can be done by launcher but I wish this feature added if it's possible.

I have tried to check/uncheck the "Use Exclusive Fullscreen" opttion in game setting but both doesn't work like Borderless Fullscreen

I wish the game doesn'tt minimize when I opening other windows or programs

**Comment by bagusnl** [comment]
Hi! 
We currently have new toggle added for all games called "Borderless Window", it should be up on Preview release of Collapse right now

You can try that combined with Fullscreen toggle being off and resolution set to your current system resolution so it simulates borderless fullscreen

**Comment by cabera2** [comment]
thank you!

**Comment by bagusnl** [comment]
While at it, I will take this issue as reminder for myself to adjust the current implementation of the Borderless Screen mode

- Disable fullscreen when Borderless is on and vice versa
- Adjust the arrangement of the option 
> - Fullscreen
> - Use Exclusive Fullscreen
> - Use Borderless Screen
- Add a tooltip to change the game resolution to the current native resolution for true borderless windowed experience

**Comment by bagusnl** [comment]
The improvement to the Borderlees Screen mode is up with commit https://github.com/neon-nyan/Collapse/commit/c5ed6b3d36ae0e2a1a91dd5261ca522d61164684 and waiting for next batch of preview release. Going to close this issue as completed, feel free to reopen when you or someone have issue with this particular feature. Thank you for submitting your issue to Collapse and using Collapse as your preferred launcher of choice!

https://github.com/neon-nyan/Collapse/assets/28079733/81de93da-c5fe-4ea8-b3d3-b1138040dd06
