### ISSUE TITLE
[Bug]: Small bar appears on the bottom edge when small window is on

### ISSUE THREAD

**Issue by EAlZZZl** [neon-nyan/Collapse#227]
### Affected Version

1.70.14

### Bug Behavior

Small windows with white or black edges underneath

### Expected Behavior

Just as perfect as the large window

### Steps to reproduce

1. Open the sidebar
2. Click Program Settings
3. Window size = small

### Screenshot(s)

![image](https://github.com/neon-nyan/Collapse/assets/130824184/65d92851-a216-416f-a32c-a35178e398c7)
![屏幕截图 2023-08-12 180854](https://github.com/neon-nyan/Collapse/assets/130824184/45f5eadb-e510-4042-9ce7-85f8b5a08645)

**Comment by bagusnl** [comment]
Can confirm it does happen in Stable build in light mode, but nowhere to be seen in Preview/Debug build or on dark mode

![image](https://github.com/neon-nyan/Collapse/assets/28079733/466790f0-93d7-46e4-84b1-36d6ab98777f)
![image](https://github.com/neon-nyan/Collapse/assets/28079733/0a6226af-080d-42f8-adee-fb48e5c77298)

**Comment by bagusnl** [comment]
Closing this as new UI has been synced to main and no further update from issue Author. If there is another update that requires attention regarding this issue please reopen the ticket.

Thank you for using Collapse!
