### ISSUE TITLE
[Bug]: Can't open Mainland China's Honkai Impact 3rd Page

### ISSUE THREAD

**Issue by cocochick** [neon-nyan/Collapse#234]
### Affected Version

1.70.15

### Bug Behavior

Open Honkai Impact 3rd Mainland China page, and here is the error 

Hi3Helper.Http.HttpHelperUnhandledError: HttpResponse for URL: "https://sdk-static.mihoyo.com/bh3_cn/mdk/launcher/api/content?key=SyvuPnqL&filter_adv=false&language=zh-cn&launcher_id=4" has returned unsuccessful code: NotFound
   at Hi3Helper.Http.Http.GetSessionStream(HttpResponseMessage response)
   at Hi3Helper.Http.Http.GetSessionAsStreamAsync(String URL, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken Token)
   at Hi3Helper.Http.Http.DownloadFromSessionStreamAsync(String URL, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken ThreadToken)
   at CollapseLauncher.MainPage.TryGetSingleLangResourceProp(CancellationToken Token, PresetConfigV2 Preset)
   at CollapseLauncher.MainPage.FetchLauncherLocalizedResources(CancellationToken Token, PresetConfigV2 Preset)
   at CollapseLauncher.MainPage.TryLoadResourceInfo(ResourceLoadingType resourceType, PresetConfigV2 preset)

### Expected Behavior

The page can be opened

### Steps to reproduce

Choose  Honkai Impact 3rd Mainland China

### Additional Information

This appears to be a server error rather than my network error. Also, is it a better option to have the page display when fetching server resources fails?

**Comment by bagusnl** [comment]
Thank you for sending the issue, seems like the launcher resource page has changed for CN release. Will investigate and send update as soon as fix is available

**Comment by MisakaSakura** [comment]
Same problem, and it makes it impossible to switch to another game's startup page

**Comment by bagusnl** [comment]
If you can't use Collapse for other games because of this change, you can edit the config.ini file in `C:\Users\%USERNAME%\AppData\LocalLow\CollapseLauncher` 
Edit the `Game Region` string to Global

**Comment by bagusnl** [comment]
# Issue Identified

Launcher resource URI changed, working on Collapse Metadata update

**Comment by bagusnl** [comment]
# Metadata Update Pushed

Please restart Collapse and let it do metadata update. If the error persists, try restarting Collapse once again.

If there is problem regarding HI3 6.9 update for Collapse, feel free to chime in here.

**Comment by sino1641** [comment]
HI Bagusnl,
Thanks for the quick fix regarding official resources change.
But for Collapse public preview I am using, it still shows Paimon failed after I restarted Collapse a few times.
From log I can see there is no metadata update:
````Shell
[Schm]  Running Collapse Launcher [1.71.6], [Preview], under Windows 11 (build: 22621.0), as  
[Schm]  Runtime: .NET 7.0.9 - WindowsAppSDK 1.3
[Schm]  Locale file: en-us.json loaded as English by neon-nyan, CryoTechnic
[Schm]  Locale file: es-419.json loaded as Español (LATAM) by BloodDragooner, d-l-n, IhoFox
[Schm]  Locale file: id-id.json loaded as Bahasa Indonesia by neon-nyan, bagusnl
[Schm]  Locale file: ja-jp.json loaded as 日本語 by Vermilion-Shinsha
[Schm]  Locale file: ko-kr.json loaded as 한국어 by despenser08
[Schm]  Locale file: pt-pt.json loaded as Português (Portugal) by gablm
[Schm]  Locale file: ru-RU.json loaded as Русский by ChocolateNao
[Schm]  Locale file: vi-vn.json loaded as Tiếng Việt by kleqing
[Schm]  Locale file: zh-cn.json loaded as 简体中文 by misaka10843, imgradeone, SatoSouta
[Schm]  Locale file: zh-TW.json loaded as 繁體中文 by Seria Ati
[Info]  Welcome to Collapse Launcher v1.71.6 - Windows 11 (build: 22621.0) 
[Info]  Getting CDN Content from: Cloudflare at URL: https://r2.bagelnl.my.id/cl-cdn/notification_preview.json
[Info]  Getting CDN Content from: Cloudflare at URL: https://r2.bagelnl.my.id/cl-cdn/squirrel/preview/RELEASES?arch=x64&os=windows&id=Collapse&localVersion=1.71.6
[Info]  Cur. Session Region Hash: -1280661324 (1692205612 - Honkai Impact 3rd - Southeast Asia)
[Info]  Cur. Session Region Hash: -1860019383 (1692205612 - Honkai Impact 3rd - Global)
[Info]  Cur. Session Region Hash: -291162813 (1692205612 - Honkai Impact 3rd - Mainland China)
[Info]  Cur. Session Region Hash: 944405822 (1692205612 - Honkai Impact 3rd - TW/HK/MO)
[Info]  Cur. Session Region Hash: -1488390735 (1692205612 - Honkai Impact 3rd - Korea)
[Info]  Cur. Session Region Hash: -551936613 (1692205612 - Honkai Impact 3rd - Japan)
[Info]  Cur. Session Region Hash: -585101950 (1692205612 - Genshin Impact - Global)
[Info]  Cur. Session Region Hash: 1162971886 (1692205612 - Genshin Impact - Mainland China)
[Info]  Cur. Session Region Hash: 66146565 (1692205612 - Honkai: Star Rail - Global)
[Info]  Cur. Session Region Hash: -1801903224 (1692205612 - Honkai: Star Rail - Mainland China)
[Schm]  Initializing Honkai Impact 3rd - Mainland China...
[Warn]  Loading Game: Honkai Impact 3rd - Mainland China has timed-out (> 15 seconds). Retrying...
[Warn]  Loading Game: Honkai Impact 3rd - Mainland China has timed-out (> 20 seconds). Retrying...
[Warn]  Loading Game: Honkai Impact 3rd - Mainland China has timed-out (> 25 seconds). Retrying...
[Warn]  Loading Game: Honkai Impact 3rd - Mainland China has timed-out (> 30 seconds). Retrying...
[Warn]  Loading Game: Honkai Impact 3rd - Mainland China has timed-out (> 35 seconds). Retrying...
[Info]  Getting CDN Content from: Cloudflare at URL: https://r2.bagelnl.my.id/cl-cdn/preview/fileindex.json
[Info]  Getting CDN Content from: Cloudflare at URL: https://r2.bagelnl.my.id/cl-cdn/metadata/metadatav2_previewstamp.json
```
Please share with us if there is a force way to refresh the latest metadata, thanks.

**Comment by bagusnl** [comment]
@sino1641 Seems like currently Collapse wants to load the Region first before trying to update metadata, we will look on this soon. But to mitigate your current issue you can edit Collapse's config.ini in `C:\Users\%USERNAME%\AppData\LocalLow\CollapseLauncher`

Change its `GameRegion` and/or `GameCategory` to anything other than Maindland China // Honkai Impact 3rd then relaunch Collapse. Collapse will soon then reload to another region and tries to download the latest metadata.

You can also download the metadata here https://r2-render.bagelnl.my.id/cl-cdn/metadata/metadatav2_previewconfig.json and overwrite the metadata.json file inside your Collapse Data folder with everything inside the new file

We are sorry for the inconvenience this have caused
