### ISSUE TITLE
[Bug]: Download stuck on 9.54GB

### ISSUE THREAD

**Issue by EnergoStalin** [neon-nyan/Collapse#235]
### Affected Version

1.71.6-PRE

### Bug Behavior

It stuck's around 9.54GB of first package and then not let continue doing seemingly nothing cause no progress shown or i can see any activity in task manager. When restart and try to continue after some time produces unhelpful "Session has been disposed during initialization!" error.
[log-2023-08-18-pre1.71.6-id1.log](https://github.com/neon-nyan/Collapse/files/12374325/log-2023-08-18-pre1.71.6-id1.log)
[DxDiag.txt](https://github.com/neon-nyan/Collapse/files/12374327/DxDiag.txt)

### Expected Behavior

Continue download

### Steps to reproduce

1. Start download
2. Wait until 9.54GB

### Screenshot(s)

https://github.com/neon-nyan/Collapse/assets/49844515/72558ac5-09b7-44c9-a447-ec639e001ffc

### Additional Information

It persist in stable build as well after moving into PRE nothing changed except download progress fixed #210.

Starting over again works fine. Until stucking on 9.54GB...

**Comment by bagusnl** [comment]
Hi, thank you for submitting bug reports regarding Collapse!
While we investigate said issue, can you do a full disk check on the drive you are trying to install to? 
Steps to do:
1. Close Collapse and other programs
2. Run Command Prompt with Administrator privileges
3. Enter this command `chkdsk C: /scan /R /perf /forceofflinefix`
4. Wait until its done and restart
5. Try again

**Comment by EnergoStalin** [comment]
![Screenshot 2023-08-18 045943](https://github.com/neon-nyan/Collapse/assets/49844515/2db8f1a0-f539-4c76-81d7-6052f243b3eb)

Now it wont resume at all. Start over works as expected stucking on 9.54GB.
![image](https://github.com/neon-nyan/Collapse/assets/49844515/9735e866-3f8b-4085-9b22-e22fae1a8c3a)
![image](https://github.com/neon-nyan/Collapse/assets/49844515/1be4470c-734a-425b-a4c7-7ef5d5f27bb4)

**Comment by bagusnl** [comment]
Kind of want to confirm, is there no network activity when the download is stuck?

**Comment by EnergoStalin** [comment]
Yes

**Comment by bagusnl** [comment]
Will ask some others to check this issue out, but for now leave it downloading like that for a couple minutes or so. In hope that its just CDN connection issue to your area

**Comment by EnergoStalin** [comment]
Thanks for the tip actually yesterday deleted StarRail to play some genshin. It automatically cancel download after minute or so with `"[Erro]  Session has been disposed during initialization!"` so it wont continue downloading even if i leave it

Ps: Project looks cool i like the UI stuff along with tools section. I wish to see brandwidth limiting but it can be achieved in other ways so it's not really worth implementing i think.

**Comment by bagusnl** [comment]
I've just thought of another idea, since some of your chunks seems to be failing to connect and download, can you try lowering your download thread to 4 or even 1?
One of our dev tried downloading GI like you just yesterday and found no issue so we are kind of leaning to connection issue in your area

**Comment by EnergoStalin** [comment]
It was 2 threads all the time
![image](https://github.com/neon-nyan/Collapse/assets/49844515/9d9324e4-79af-4976-9476-5f9f70d690c5)

Will try download with aria2

**Comment by EnergoStalin** [comment]
Okay aria also failed to download looks like file broken
![image](https://github.com/neon-nyan/Collapse/assets/49844515/fdd62cdf-7c7b-4976-b1f9-744284f7c093)

But holy with some random proxy it works again
![image](https://github.com/neon-nyan/Collapse/assets/49844515/d13d4479-9efa-480e-82e9-a696129b7ac0)

Provider has different servers for regions?

**Comment by bagusnl** [comment]
HYV download CDN usually just Akamai CDN sitting on top of Alibaba OSS (S3 bucket), could be Akamai is having some problem in your area right now.

Closing this as identified not a Collapse issue, but feel free to chime in still or re-open the issue if for some reason the bug keeps happening.

Thank you for using Collapse!

**Comment by EnergoStalin** [comment]
Windows proxy hotfix
```js
/**
 * @param {string} url 
 * @param {string} host 
 */
function FindProxyForURL(url, host) {
  if(url.includes("autopatchhk.yuanshen.com"))
    return "PROXY <any http/https proxy here in format host:port>"

  return "DIRECT"
}
```
