### ISSUE TITLE
[Request]:Where is my "Game Repair" button?

### ISSUE THREAD

**Issue by yjc20061008** [neon-nyan/Collapse#239]
**Is your feature request related to a problem? Please describe.**
I can't repair the game "Genshin  Impact(Mainland China)".

**Describe the solution you'd like**
Add the "Game Repair" button.

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/neon-nyan/Collapse/assets/94227484/9787be6c-551b-4949-beb1-a17fe20c8da5)
Where is my "Game Repair" button?

**Comment by bagusnl** [comment]
Thank you for reporting this issue, please try restarting your launcher and letting it update its metadata. Repair function should be back after the metadata is updated

**Comment by yjc20061008** [comment]
![image](https://github.com/neon-nyan/Collapse/assets/94227484/22ae99a8-9b33-4293-bbfd-a6050076e334)
Thank You!The problem is solved now.

**Comment by bagusnl** [comment]
You're welcome!
Thank you for using Collapse Launcher <3
