### ISSUE TITLE
[Bug]: Can't get Into Genshin

### ISSUE THREAD

**Issue by josephisticated** [neon-nyan/Collapse#240]
### Affected Version

Collapse 1.70.15

### Bug Behavior

Can't go into Genshin's page in launcher.

### Expected Behavior

Normal Genshin page should have opened.

### Steps to reproduce

1. Run the app
2. See the action timed out notification
3. Wait
4. Get the Your Internet is Disconnected screen

### Screenshot(s)

![image](https://github.com/neon-nyan/Collapse/assets/53388005/3d82176d-004e-42c9-adaa-a1e68712b494)
![image](https://github.com/neon-nyan/Collapse/assets/53388005/604d09b2-e774-446d-bdbe-5fab8c8394f8)
![image](https://github.com/neon-nyan/Collapse/assets/53388005/e72fbfb5-9099-4e6e-8461-fc63504fa068)
![image](https://github.com/neon-nyan/Collapse/assets/53388005/ae1c35bd-ef2b-44f4-aef5-101f4b69fed9)
![image](https://github.com/neon-nyan/Collapse/assets/53388005/509b7ef2-407c-4c2b-9902-2fa0e2d800a2)

**Comment by bagusnl** [comment]
Hi! Thank you for reporting issue in Collapse Launcher
workaround for this exact issue has been up, please relaunch Collapse

**Comment by josephisticated** [comment]
> 1. Change region to something else
> 2. Go to Collapse Settings
> 3. press "Open app data folder"
> 4. Go to `_metadata`
> 5. Delete the 2 files in there

Tried two times now, still not working.

**Comment by muscularcandy67** [comment]
Try instead to delete the entire _metadata folder

**Comment by josephisticated** [comment]
> Try instead to delete the entire _metadata folder

Nope, still not working.

**Comment by bagusnl** [comment]
[_metadata.zip](https://github.com/neon-nyan/Collapse/files/12395827/_metadata.zip)
put the 2 files inside this zip file on the _metadata folder
![image](https://github.com/neon-nyan/Collapse/assets/28079733/4782c817-73b8-4478-be7a-0768fc734672)

**Comment by josephisticated** [comment]
> [_metadata.zip](https://github.com/neon-nyan/Collapse/files/12395827/_metadata.zip) put the 2 files inside this zip file on the _metadata folder

Worked for a sec, then updated itself automatically made itself not work again.

**Comment by muscularcandy67** [comment]
Can  you send the metadataV2 here?

**Comment by bagusnl** [comment]
Since you are using an older version of Collapse, can you try newer preview version?
You can switch to preview build on Collapse settings page

**Comment by josephisticated** [comment]
[metadatav2.json](https://qiwi.gg/file/2UIEn4xDQUPFdGWGQOYOUiUGJfq-557377-metadatav2) and [stampv2.json](https://qiwi.gg/file/2UIEn4xDQUPFdGWGQOYOUiUGJfq-97383-stampv2)

**Comment by josephisticated** [comment]
Says that they don't support that file type.

**Comment by muscularcandy67** [comment]
Zip the folder and send

**Comment by josephisticated** [comment]
[_metadata.zip](https://github.com/neon-nyan/Collapse/files/12395976/_metadata.zip)

**Comment by muscularcandy67** [comment]
Which CDN are you using?

**Comment by josephisticated** [comment]
> Which CDN are you using?

jsDelivr

**Comment by muscularcandy67** [comment]
Ah deprecated

**Comment by josephisticated** [comment]
> Ah deprecated, try switching to cloudflare/bitbucket/github

Worked like a charm thanks and sorry y'all 🙏.
