### ISSUE TITLE
Migrating a game from the usual Launcher, is it possible?

### ISSUE THREAD

**Issue by pphu15** [neon-nyan/Collapse#245]
Is it possible to use Collapse raw without keeping the Launcher of each game? What to do if I have the game fully installed and neither Hoyoverse app where it's bundled nor if Collapse can detect the install?

**I could be able to execute Genshin raw like eating a fish without cooking it.**
![image](https://github.com/neon-nyan/Collapse/assets/128244304/354bdd33-1b77-45b7-b7d7-62c70d90c664)
![image](https://github.com/neon-nyan/Collapse/assets/128244304/65b27614-b69d-497f-b202-6e547f380525)

**Comment by bagusnl** [comment]
You should be able to oress Install/Locate Game on the game screen then go to that folder. If it doesn't detect it, make sure the app.info file inside GenshinImpact_Data is there and contains these lines

```
miHoYo
Genshin Impact
```

**Comment by bagusnl** [comment]
You should be able to oress Install/Locate Game on the game screen then go to that folder. If it doesn't detect it, make sure the app.info file inside GenshinImpact_Data is there and contains these lines

```
miHoYo
Genshin Impact
```
Also please make sure the Genshin impact game folder is not inside the same folder that Collapse Launcher is installed in, move it to another folder

**Comment by pphu15** [comment]
I just done moving the game folder out of Collapse Launcher install directory, and whilst found the app.info file, it cannot detect.
Moreover, both apps don't work. 
![image](https://github.com/neon-nyan/Collapse/assets/128244304/c4ae7bd2-a098-4aaa-afcf-69451c483f5a)

**Comment by pphu15** [comment]
> I just done moving the game folder out of Collapse Launcher install directory, and whilst found the app.info file, it cannot detect. Moreover, both apps don't work. ![image](https://user-images.githubusercontent.com/128244304/262621314-c4ae7bd2-a098-4aaa-afcf-69451c483f5a.png) There is guaranteed two lines in the file.

I had to uninstall the typical Genshin Impact launcher and switch to yours to diagnose this. Still, everyone mandates me a game reinstall?

**Comment by bagusnl** [comment]
With Collapse console in the setting turned on, can you record the process on which you use the locate game function?

**Comment by pphu15** [comment]
![image](https://github.com/neon-nyan/Collapse/assets/128244304/1fac3f37-7893-4f6b-8664-694a1ac3c82c)
Status: not installed. Whilst there's all files + English (US) audio
It's still say the not-installed state.

**Comment by bagusnl** [comment]
Can you send me what the contents of your config.ini file?

**Comment by pphu15** [comment]
![image](https://github.com/neon-nyan/Collapse/assets/128244304/6af41b63-3082-42a2-a6b8-e066ca53d003)

```
[General]
uapc=ded3ab92053a
```

**Comment by bagusnl** [comment]
Ahhh, seems your config.ini file isn't complete

Here's mine, copy it to your installation. Make sure the version string is the same as the one you've installed right now (you can check by opening the game and see the string on the bottom left followed by OSRel)
```
[General]
channel=1
cps=mihoyo
game_version=4.0.0
sub_channel=0
sdk_version=
plugin_7_version=1.0.0
```

**Comment by pphu15** [comment]
Confirmed, thanks.
![image](https://github.com/neon-nyan/Collapse/assets/128244304/c3c10f43-2039-4e15-a4d2-c7c8fdcf674d)
