### ISSUE TITLE
[Genshin Impact] Issue in Mainland China Game Repair | Getting a Mainland China Account

### ISSUE THREAD

**Issue by bagusnl** [neon-nyan/Collapse#247]
Hello Collapse users!
Our repair function for Genshin Impact in Mainland China region is currently broken as of last 4.0.1 hotfix update. After the update, our old Dispatcher Key is expired and need a new one. While I can outsource someone to grab the keys, I believe this way isn't the best as I would have to bother someone else to grab the key once an update is dropped.

I am looking for a way to get a Mainland China account. But as it seems, as outsider, it's quite hard to do so. Or I'm just not as experienced at it. If someone has knowledge on how I can get one, please let me know either here, my Discord (ping me (@bagusnl) on Collapse server), or via email bagusnl@protonmail.com.

Or if you have the knowledge to just grab me the key every time there is an update, then you can send the dispatcher key one the same way as to contact me above.

**Comment by Winter-is-comingXK** [comment]
What account do you need?
mihoyo?it needs a mobile phone number in chinese Mainland. If you need, I can help you

**Comment by bagusnl** [comment]
@Winter-is-comingXK we need mhy account that can be used to login to the China client yes

**Comment by Winter-is-comingXK** [comment]
I have joined Discord, hao can i give you account

**Comment by MoonShadowIllusion** [comment]
i have send email to you
