### ISSUE TITLE
[Request] Improved translation

### ISSUE THREAD

**Issue by xTaiwanPingLord** [neon-nyan/Collapse#254]
I have made some improvements in PR #196. However, they did not sync to Crowdin and were reverted in commit 10652a4. 
Now I have made the improvements again in Crowdin. Could someone please review them? (Traditional Chinese and some Simplified Chinese)

**Comment by bagusnl** [comment]
we are really sorry for reverting your translation, I'll try to find some time to review your translations in crowdin.
also thank you so much for providing translation for collapse <3

**Comment by bagusnl** [comment]
Closing this as discussed in Discord localizer channel
