### ISSUE TITLE
[Bug]: Collapse's automatic update runs twice, resulting in an error, but an successful update will occur

### ISSUE THREAD

**Issue by Cactism** [neon-nyan/Collapse#258]
### Affected Version

Collapse 1.71.8 Stable

### Bug Behavior

The following is what appears to be happening in my eyes:

If the launcher finds a new version as it starts up, an automatic update pop-up will appear. While the update banner is counting down, the launcher also initializes the game page behind the popup. After the game page is initialized, another automatic update pop-up will appear, overlaying itself over the former pop-up. While the former automatic update is downloading the updated launcher, the latter will still countdown. Once the latter update finishes counting down, an error will be spat out (see the console log at the bottom).

While the update will still eventually finish successfully despite the error (as the former update will complete the update), this just seems to be not very intuitive and user friendly.

### Expected Behavior

Collapse should only have one update pop-up at a time - this can be remediated possibly by checking for automatic updates once at startup.

### Steps to reproduce

1. Have an outdated Collapse Launcher
2. Wait for an automatic update pop-up
3. Wait for the second automatic update pop-up
4. Wait for the second automatic update pop-up's countdown to finish
5. An error will appear.

### Additional Information

After uninstalling and reinstalling the same old version of the launcher (Collapse 1.71.8 Stable), I can't seem to reproduce the issue. This issue also happened on my other computer.

Console Log: [log-2023-09-05-sta1.71.8-id1.log](https://github.com/neon-nyan/Collapse/files/12528167/log-2023-09-05-sta1.71.8-id1.log)
`dxdiag.txt`: [DxDiag.txt](https://github.com/neon-nyan/Collapse/files/12528173/DxDiag.txt)

**Comment by bagusnl** [comment]
Fix is up on the commit, will close this once this commit is pushed to a preview version

**Comment by bagusnl** [comment]
Commit with this fix has already been pushed to release, so we are going to close this issue. Should the same issue or related occurs again, feel free to reopen the issue

Thank you for reporting issue for Collapse project <3
