### ISSUE TITLE
[Request] Adding CN Cutscenes to Honkai Impact 3rd

### ISSUE THREAD

**Issue by Cactism** [neon-nyan/Collapse#259]
## Is your feature request related to a problem? Please describe.
I find it quite annoying that there are no Chinese cutscenes (CGs) built into the Honkai Impact 3rd overseas versions of the game. As someone who uses Chinese voice-over to play the game, it's quite immersion breaking when there's a Japanese CG in the middle of the Chinese dubbed story (no hate to the Japanese voiceover + voice actors, this is just my personal preference 😄). 

## Describe the solution you'd like
An option that is available within the Collapse Launcher that replaces the Japanese dubbed CGs within the CG folder (`...\Games\BH3_Data\StreamingAssets\Video`) with Chinese ones (with English - or more languages - subtitles built into the CG file).
- This can happen by downloading the Chinese cutscenes with subtitles (already created by someone) and replacing them with the Japanese ones,
- or by downloading the Chinese CGs directly from the CN client from miHoYo's servers (is this really possible?) and replacing the audio from the Japanese CGs with the Chinese CGs - I've suggested this method as simply replacing the CGs from the CN client to the overseas' client will result in no subtitles. Replacing the audio will retain the subtitle data from the Japanese CGs.

## Describe alternatives you've considered
- Replacing the CGs manually with Chinese CGs from the official Honkai Impact 3rd Discord server at [this](https://discord.com/channels/418652140454674432/427673685026013184/936763213213741127) message.
  - While this method does work, waiting for others to compile the CGs is not a time-effective approach (I've done the v6.6-6.8 Chinese CGs myself as a result heh).

- Download the CN client → grab the Chinese CGs → replace the Japanese CGs' audio with the Chinese ones → rename the file so the game recognizes the CG file → replace the new CG files into the game
  - Doing all of this simply to get the Chinese CGs manually is just too much of a hassle.

### What do you mean by "replacing the audio of the Japanese CGs with the Chinese ones"?
The Chinese CGs by themselves do not have English subtitles for example, so using this [program](https://github.com/guzenco/USM_Audio_chunks_rewriter) will produce Chinese CGs while retaining the subtitle data within the Japanese CGs.

### Why must you "rename the file so the game recognizes the CG file"?
You must retain the CG file name of the client you are using in order for the game to use the Chinese CGs.

---
I understand that the amount of people within the player-base who use Chinese voiceover is quite small (from what I keep hearing), but having this as feature will be a huge plus for someone who does.

Thank you for taking your time reading this - if you have any questions about what I wrote, please let me know and I'll answer them to the best of my knowledge.

**Comment by bagusnl** [comment]
Thank you for filling in Collapse enhancement request form!
I'm not sure about this as after the conversion is done, then the CGs will always get flagged as "Corrupted" in Game Repair. While we can circumvent this by ignoring all CGs repair when a flagger file (dummy file that states CGs are intentionally modified) can be done, this will break quite a lot of things like incomplete Game Repair (as it can't check any CG files), also delta patch might be broken by it.

While I personally can't find a way on how to properly implement this function in Collapse, others feel free to chime in their opinion on the matter.

**Comment by bagusnl** [comment]
We will discuss this further with the other devs!

**Comment by bagusnl** [comment]
Hi~
Sorry that it took quite a while until we could answer this issue. But unfortunately, after discussing with neon about this request we have to come with conclusion that we can't implement this behavior to Collapse project. The reason being is that we try to not implement any feature that modifies game assets directly outside of what HoYo provides via their APIs and CDNs. 

As your request is about modifying HI3 CG to use CN VA instead of JP for Global release falls outside the scope of what we can implement currently.

Should our policy about this (modifying game assets outside HoYo's intent) change in the future, feel free to reopen or remake the issue for us to rediscuss about this matter further.

We are really sorry for the delay and the decline, I hope you understand.
Thank you for keep supporting Collapse project <3
