### ISSUE TITLE
[Request] translation

### ISSUE THREAD

**Issue by iidoki** [neon-nyan/Collapse#266]
**Is your feature request related to a problem? Please describe.**
hi, i have no idea how to ask but im looking to translate this software in italian. can i do this? are these some things i should know? sorry for bothering

**Describe the solution you'd like**
italian translation :)

**Describe alternatives you've considered**

**Additional context**

**Comment by tilsgee** [comment]
crowdin

**Comment by tilsgee** [comment]
https://crowdin.com/project/collapse-launcher

**Comment by bagusnl** [comment]
Crowdin OSS license we have is still having some problems. We'll nudge neon to add Italian language support there and let you know when he responded

**Comment by iidoki** [comment]
i mean, i would like to provide the italian translation for this software. im just asking if there are some things i need to do first or stuff i should know ^^

**Comment by Cryotechnic** [comment]
> i mean, i would like to provide the italian translation for this software. im just asking if there are some things i need to do first or stuff i should know ^^

There is nothing to be done on your end, it's something on our end. We'll let you know once it's ready for translation!

**Comment by iidoki** [comment]
alright, thank you!
