### ISSUE TITLE
[Bug]: Show "Your Internet is Disconnected" when switch game to Star Rail

### ISSUE THREAD

**Issue by yaxuan97** [neon-nyan/Collapse#267]
### Affected Version

Collapse 1.71.10

### Bug Behavior

After I switched the game to Honkai:StarRail(Mainland China). Then happened.
errorMessage:
System.NullReferenceException: Object reference not set to an instance of an object.
   at CollapseLauncher.MainPage.DownloadBackgroundImage(CancellationToken Token) in W:\GitHub Repos\Collapse\CollapseLauncher\Classes\RegionManagement\RegionManagement.cs:line 179
   at CollapseLauncher.MainPage.FetchLauncherLocalizedResources(CancellationToken Token, PresetConfigV2 Preset) in W:\GitHub Repos\Collapse\CollapseLauncher\Classes\RegionManagement\RegionManagement.cs:line 169
   at CollapseLauncher.MainPage.TryLoadResourceInfo(ResourceLoadingType resourceType, PresetConfigV2 preset) in W:\GitHub Repos\Collapse\CollapseLauncher\Classes\RegionManagement\RegionManagement.cs:line 135

After that, I can't switch the game to another game. And I cannot access the program settings through the GUI.
![image](https://github.com/neon-nyan/Collapse/assets/11773871/5337763f-463b-4b0f-b9e1-06f79b301c35)

Here is some warning in console:
![image](https://github.com/neon-nyan/Collapse/assets/11773871/a7b51c95-3f2d-4b53-a556-183896c33be0)

I'm sure there's nothing wrong with my internet connection: the other game's pages are accessible and I can run StarRail through the official launcher. I've tried modifying proxy settings and resetting my internet connection, neither of which solved the problem.

[log-2023-09-20-sta1.71.10-id1.log](https://github.com/neon-nyan/Collapse/files/12667742/log-2023-09-20-sta1.71.10-id1.log)
[DxDiag.txt](https://github.com/neon-nyan/Collapse/files/12667761/DxDiag.txt)

### Expected Behavior

1. This problem came out of nowhere this morning. I was playing the game normally last night. I'm not sure what went wrong.
2. Even if an error occurs, I recommend that the program not prevent the user from switching to other pages that can be accessed normally, such as program settings.

### Steps to reproduce

To reproduce the problem, I did:
1. Reset the program's configuration file (C:\Users\username\AppData\LocalLow\CollapseLauncher\config.ini)
2. restart the program and switch the game to StarRail

### Screenshot(s)

![info](https://github.com/neon-nyan/Collapse/assets/11773871/bf7612b5-7633-427d-9bed-30ccf0078130)

### Additional Information

In my tests, only the region "Mainland China" has this problem. Selecting "Global" allows you to access the page normally.

**Comment by Tachibana-Kin** [comment]
I’d like to share something I found. 
As the same, I couldn't open Honkai Star Rail(China Mainland) with my local network.
when I open Collapse with my clash on, this bug (might be) has been solved. 
![屏幕截图 2023-09-20 104250](https://github.com/neon-nyan/Collapse/assets/19606268/c1010450-b77a-47ab-96cc-0b38cf3e43b4)
Just a normal try. (Because I can't access to Github with local network today.)

**Comment by yaxuan97** [comment]
It auto resolved at about 1 hours ago.

**Comment by yaxuan97** [comment]
It auto resolved at about 1 hours ago.
