### ISSUE TITLE
[Bug]: Can't interact with UI after the notification center poped up

### ISSUE THREAD

**Issue by guch8017** [neon-nyan/Collapse#268]
### Affected Version

1.71.10

### Bug Behavior

After launch the launcher, everything is normal. Then the notification centre pop up automatically showing that the launcher has been updated. After closing the notification, the UI doesn't respond to any operation except minimize or close the application. 

Or if I open the notification centre manually, the problem will also occur.

[log-2023-09-20-sta1.71.10-id1.log](https://github.com/neon-nyan/Collapse/files/12668738/log-2023-09-20-sta1.71.10-id1.log)

### Expected Behavior

Can interact with the launcher after closing the notification.

### Steps to reproduce

1. Launch the launcher.
2. Open the notification by clicking the icon.
3. Close the pop up window.

### Screenshot(s)

https://pan.guch8017.top:10006/s/fXspt2ietrxL5Aw

A screen record is provided here.

**Comment by bagusnl** [comment]
This should be fixed on the latest stable release. As such this issue will be closed for now. Should this issue or similar reappears, feel free to reopen or make a new one.

Thank you for the support on Collapse project <3
