### ISSUE TITLE
[Bug]: Unable to switch back to the game that was selected when Collapse launched

### ISSUE THREAD

**Issue by OOPMan** [neon-nyan/Collapse#271]
### Affected Version

Collapse 1.7.10

### Bug Behavior

After launching Collapse, if I switch from HSR/HI3 to HI3/HSR and then attempt to switch back, the change button is not active and I cannot change changes. Weirdly, switching to GI does not exhibit this issue. I'll demonstrate with a screenshot flow:

1. Initial launch state:
![image](https://github.com/neon-nyan/Collapse/assets/248980/209b965d-0a39-4dcb-acd8-8e09e31336af)

2. Switch to HSR
![image](https://github.com/neon-nyan/Collapse/assets/248980/5c0db9d9-cdf0-40e3-9387-d0a941f8dc6d)
![image](https://github.com/neon-nyan/Collapse/assets/248980/401fcc1f-c8d2-4dda-9ca2-810ce487de7c)
![image](https://github.com/neon-nyan/Collapse/assets/248980/e6faaaa7-1324-49c0-9270-65c8c8c4b2ce)

3. Attempt to switch back to HI3
![image](https://github.com/neon-nyan/Collapse/assets/248980/25df24d3-f60d-4686-804c-6ea794d9f7c6)

4. I can switch to GI tho...
![image](https://github.com/neon-nyan/Collapse/assets/248980/75a6c4e0-644e-4a4d-8039-7064ab2053ee)
![image](https://github.com/neon-nyan/Collapse/assets/248980/56df98a2-a6d6-4eb7-87c9-00dd5e77adc8)
![image](https://github.com/neon-nyan/Collapse/assets/248980/18773829-adff-4d8a-93e9-2beb39115347)

5. I can't switch to HI3 from GI tho...
![image](https://github.com/neon-nyan/Collapse/assets/248980/eda486fb-a8e6-4de7-8f99-c9b157b4e7f7)

6. But I can switch back to HSR
![image](https://github.com/neon-nyan/Collapse/assets/248980/971a5aec-2a86-4e30-936e-19bcefee0f9b)
![image](https://github.com/neon-nyan/Collapse/assets/248980/a730a495-2037-4a21-90ae-4a115072eb86)

7. But can't switch to HI3
![image](https://github.com/neon-nyan/Collapse/assets/248980/97a82269-9a1a-4f98-b8b4-5f2a7c5946de)

If I exit Collapse and then re-open it at this point, it will launch with HSR and I can then switch to HI3...but can't switch back to HSR if I do so

### Expected Behavior

I should be able to switch between games with no issues

### Steps to reproduce

See above

### Additional Information

[log-2023-09-22-sta1.71.10-id1.log](https://github.com/neon-nyan/Collapse/files/12701783/log-2023-09-22-sta1.71.10-id1.log)

**Comment by bagusnl** [comment]
Can you try switching to preview in Settings>Switch to Preview and see if the behavior still the same?

**Comment by OOPMan** [comment]
> Can you try switching to preview in Settings>Switch to Preview and see if the behavior still the same?

That fixed it. Thanks.

**Comment by OtakuKuro** [comment]
> > Can you try switching to preview in Settings>Switch to Preview and see if the behavior still the same?
> 
> That fixed it. Thanks.

Excuse me, where can i find the Switch to Preview?

**Comment by bagusnl** [comment]
@OtakuKuro its under Collapse' settings page, on the right panel
Anyways, this bug should be fixed in the latest update, please restart Collapse and let it update

**Comment by OtakuKuro** [comment]
> @OtakuKuro its under Collapse' settings page, on the right panel Anyways, this bug should be fixed in the latest update, please restart Collapse and let it update

I`m in 1.71.11 now. I think it`s the lastest one in stable.
I try to upgrade in 1.72.1 in Preview. It fixed the question. Thanks

**Comment by Cryotechnic** [comment]
Closing since the issue has been resolved in the newer builds.
