### ISSUE TITLE
[Request]: Add a refresh button at main ui to refresh event panels

### ISSUE THREAD

**Issue by stevenghost** [neon-nyan/Collapse#322]
### Is your request related to a problem?

No

### Describe your proposed solution

Add a refresh button at main ui to refresh event panels

### Describe alternatives you've considered

I use collapse for custom star-up args, and I don't play games except genshin.
So I always stay on the genshin ui for days and the event panels won't refresh unless I change region or restart app.
A refresh button or auto refresh by game ended will be nice ty 🙏

**Comment by bagusnl** [comment]
Hello~
Thank you for submitting feature enhancement request!

Our team @gablm has worked on adding F5 functionality to refresh the region (thus all event pages and its related stuff like game updates). The current implementation doesn't have any visible button, reason being is that we always associate F5 with refresh function., thus a visible button doesn't seem to be required. 

What do you think about this solution? Let us know for any feedback
