### ISSUE TITLE
[Bug]: Collapse Settings Crash

### ISSUE THREAD

**Issue by pha1n0q** [neon-nyan/Collapse#331]
### Affected Version

Collapse v1.72.9d Preview

### Bug Behavior

Collapse crashes when you open the settings panel.

### Expected Behavior

The launcher should open the settings panel without crashing.

### Steps to reproduce

1. Open Collapse
2. Click the settings icon on the bottom left
3. Collapse crashes

### Screenshot(s)

https://github.com/CollapseLauncher/Collapse/assets/88598340/23111765-e7a9-4bd1-9d8e-54f73bf303a9

### Additional Information

Console log: [log-2023-12-03-pre1.72.9-id1.log](https://github.com/CollapseLauncher/Collapse/files/13542078/log-2023-12-03-pre1.72.9-id1.log)

**Comment by bagusnl** [comment]
Should be fixed now with 1.72.10
Sorry for the inconvenience!
