### ISSUE TITLE
[Tracking] Command-line arguments that work with Genshin Impact

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/Collapse#37]
Although most of the commands present in this [site](https://docs.unity3d.com/Manual/PlayerCommandLineArguments.html) should work, I'm gonna test each one of them and track which works and which doesn't, while trying every combo I can think of.

**WORKS**
-popupwindow 
-window-mode

**DOESN'T WORK***
-force-glcore
-force-vulkan
-force-d3d12
-no-stereo-rendering

**Comment by neon-nyan** [comment]
I've tried force-d3d12 before but the result is a glitch on the graphics. I don't know if it will be silently ignored by the game engine because I've never did some experiments since then.

I think it's better for us to make a wiki for this only topic.

**Comment by muscularcandy67** [comment]
For me it launches with the argument but the game will actually skip the command and load in DRD11 (the info comes with RivaTunerStatistic and MSI Afterburner)

**Comment by bagusnl** [comment]
I've tested some combination:
1. `-screen-fullscreen 1 -window-mode exclusive -popupwindow`
> Loads to the loading menu, but game stalls after the "loading door"



2. `-screen-fullscreen 1 -window-mode exclusive`
> Game loads fully but after alt tab it turns into black screen and stalls (NOTE: NEED TEST ON NVIDIA, AMD Driver is kindof bad at the moment on exclusive fullscreen games)
![image](https://user-images.githubusercontent.com/28079733/197523196-05c34cab-6f61-4819-8054-b98c675dc94b.png)

3. `-screen-fullscreen 1 -window-mode borderless -popupwindow`
> Works fine but no freesync :(




Some standalone command that is accepted by the game:
```
-force-driver-type-warp || (idk why someone would use this but hell yeah SW rendering)
-force-gfx-direct || single threaded woooooooooo, also texture breaks with this 
-show-screen-selector
```
Some standalone command that didn't work:
```
-force-feature-level–10–0
-force-feature-level–10–1
-force-feature-level–11–0
-force-opengl || InitializeEngineGraphics failed
```

Notes:
`-force-gfx-direct` result:
![image](https://user-images.githubusercontent.com/28079733/197526700-d185d747-6007-4354-ae05-236b7b0ffa88.png)

**Comment by bagusnl** [comment]
On 3.5 update, these command seems to get accepted by the game, but some can cause major crash to the system.
```
-force-feature-level–10–0 || shaders error, causes entire DX crash including desktop
-force-feature-level–10–1 || shaders error, causes entire DX crash including desktop
-force-feature-level–11–0 || works fine

**Comment by bagusnl** [comment]
Request closing as stale and not needed (GameSettings implemented)

**Comment by Cryotechnic** [comment]
Closing for now as there haven't been any developments on new options in a while. Will reopen if that changes though!
