### ISSUE TITLE
[Enhancement] Retain installed region when reselecting Honkai Impact

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/Collapse#39]
When I open the launcher, the launcher opens on the last selected game with the last selected region.
As of now, if I close the launcher with Honkai Global, the launcher reopens with Honkai Global, I switch to Genshin, defaults to Global, I switch again to Honkai, it defaults to Southeast Asia; if I close the launcher with Genshin Global, the launcher reopens with Genshin Global, I switch to Honkai (with only Global installed), it defaults to Southeast Asia

A nice behaviour would be I close launcher with Honkai Global, reopens with Honkai Global, switch to Genshin Global, switch to Honkai and instead of defaulting me to Southeast Asia, it selects the region actually installed.
There are two ways to go about what I'm going to suggest. One way is to select first in the list the region actually installed on game reselection if there is one, the other way is to set a default game region for the games in the global app settings, which I think would be best to avoid keeping track of installed regions

**Comment by muscularcandy67** [comment]
Compiled the 41e48175d43d362cdca22dd075dff979a782c9c6 commit and seems to be working as intended

**Comment by neon-nyan** [comment]
Yes, I just added this feature to the latest commit.
Also, if the same region doesn't exist in other game, it will fallback to the first game region

**Comment by muscularcandy67** [comment]
Closing the issue since the feature has been implemented

**Comment by bagusnl** [comment]
A nicer implementation for this would be that the launcher remembers what region of each game selected last time.
For example, I play HI3 on SEA server but on Genshin on Global (NA server), when I switch from HI3 SEA to Genshin GB and back to HI3, it should automatically picked SEA as the last opened region for HI3. Saves only 2 clicks but it sounded quite better this way

**Comment by Cryotechnic** [comment]
I believe that the launcher already has a way of tracking various game options via `config.ini` inside each game's directory. If that file is read every time the user switches games, then it could, in theory, be possible to implement a flag that updates which version of the game the user has previously selected.

**Comment by Cryotechnic** [comment]
Implemented in be81d24, so closing this issue
