### ISSUE TITLE
[Enhancement] Continuous installation while in another region/game

### ISSUE THREAD

**Issue by gablm** [neon-nyan/Collapse#44]
It would be nice for people who play more than one game/region to be able to update/download one while in another region profile.
When changing regions, the download stops and then you are forced to go back to it's profile if you want to continue it. This is inconvenient when you want to download a game while playing another without having to go to its official launcher.
I don't know if you are already planning it in the future, but if you aren't I hope you give it a thought in the near future.

**Comment by muscularcandy67** [comment]
While we are at it, an addition would be to have the download status persisting while switching region, so we can see the status anytime

**Comment by neon-nyan** [comment]
Hi there,

Thank you for the suggestion.
Yes, I'm agree with this and applicable without any code changes since the parameter that handles this behaviour is "IsRightSide" parameter on the launcher metadata for each game region.

**Comment by neon-nyan** [comment]
Unfortunately, even this request is possible, there will be a lot of code rewrite since ``Task`` mechanism need to be implemented at first. Not only that, the notification should've need to be rewritten as well to handle the ``Task`` event to get the current status of the task's completion.

But still, this is a good first issue and I will consider this feature to be implemented in the future 😁

**Comment by Cryotechnic** [comment]
Starting from 1.71.4, an early implementation of this feature has been made available. This feature will continue to evolve until it reaches a mature state in the next mainline version of Collapse. Thank you for being patient with us while we made this feature a reality!

**Comment by bagusnl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Background Download by @neon-nyan](https://trello.com/c/2lf94ubn/9-background-download-by-neon-nyan)
