### ISSUE TITLE
Language Changes Tracking: pt-PT (Português - Portugal)

### ISSUE THREAD

**Issue by neon-nyan** [neon-nyan/Collapse#50]
This issue is supposed to provide updates for the language content continuously.
The changes will be updated in every changes of the main language (en - English) so the changes can be openly contributed.

## Contributor list (So far)
* @gablm

**Comment by Cryotechnic** [comment]
Heyo @gablm

As we're preparing to launch Collapse 1.69.0, there are a couple (a lot XD) of new strings to update and review. Could you check the pt-PT strings to make sure that they match the en-US ones? Thanks :D

**Comment by neon-nyan** [comment]
Thanks for the reminder @Cryotechnic
Also @gablm, there are few changes going on with the en-US translation. If you want to make it clear what has been changed, you can take a look in this diff link:

https://github.com/neon-nyan/Collapse/compare/neon-nyan:f9b2c30...neon-nyan:b68f9ee#diff-36f59f0c9f34ce5b52d49914666242eafc8afe31099be9fa2142f5d822bd7729

**Comment by neon-nyan** [comment]
Thanks for the reminder @Cryotechnic
Also @gablm, there are few changes going on with the en-US translation. If you want to make it clear what has been changed, you can take a look in this diff link:

https://github.com/neon-nyan/Collapse/compare/neon-nyan:f9b2c30...neon-nyan:b68f9ee#diff-36f59f0c9f34ce5b52d49914666242eafc8afe31099be9fa2142f5d822bd7729

**Comment by gablm** [comment]
Hey,
Considering the changes to syntax that @Cryotechnic made to some strings, I will probably redo most of the translation.
When were you thinking of releasing version 1.69? Just to see if I'm able to do it before.
Anyways, I'll start working on the translation.
