### ISSUE TITLE
[BUG] Failed to detect HI3 Settings

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/Collapse#63]
![image](https://user-images.githubusercontent.com/12277635/206854656-6bc8139d-8137-453b-9ca8-5b0855f0d77d.png)
As you can see, the launcher thinks I have yet to launch the game once, but as you might already know, I did launch the game multiple times (I do play Honkai on a daily basis). The commit I am running is 7fd057f99048a6774da800e80bee20d23846d89a . This started since 6.2 update

**Comment by neon-nyan** [comment]
I haven't notice any key changes being made by miHoYo recently. Have you tried the Southeast Asia or other server as well?

**Comment by muscularcandy67** [comment]
I tried on Mainland China and while of course I couldn't login due to not having a cn mhy account, the launcher detected the configuration. I have yet to try on other regions

**Comment by neon-nyan** [comment]
I see, got it!
I will try to check it myself later.

**Comment by Cryotechnic** [comment]
This is the issue that I was talking to you about in [my PR](https://github.com/neon-nyan/Collapse/pull/58#discussion_r1044838389) the other day. Can confirm that it is present on GLB as well.

**Comment by neon-nyan** [comment]
This issue should've been fixed now by updating the metadata.

<img width="888" alt="image" src="https://user-images.githubusercontent.com/30566970/208683528-084302af-b742-47b7-a5ab-a311a8a001da.png">

**Comment by Cryotechnic** [comment]
Can confirm it is fixed now. Thanks!

**Comment by muscularcandy67** [comment]
Works!
![image](https://user-images.githubusercontent.com/12277635/208775570-0ce9bbe7-b914-4e4f-a2ad-8ede35d1353f.png)
