### ISSUE TITLE
[Investigate] Invalid .NET Framework version

### ISSUE THREAD

**Issue by Cryotechnic** [neon-nyan/Collapse#66]
Ever since commit c7cc999affcc6297cab5b7d154bdffc00425f882, I have been unable to locally compile Collapse, getting:

![image](https://user-images.githubusercontent.com/9833218/209107485-70339165-08f0-4a6e-9df6-bcebe0ffafde.png)

when trying to start the app. Taking a look a the changes, I found out that Microsoft published an update to .NET on December 13, 2022 (version 7.0.101). Could this be the reason that the app no longer works? Visual Studio 2022 also had an update, bumping the version to `17.4.3`.

This could be just something on my end, but considering how it was working fine yesterday and not today, this does seem suspicious.

**Comment by neon-nyan** [comment]
Seems like your Runtime and SDK didn't get updated at the same time.
Can you share the output of this command?

```
dotnet --list-sdks && dotnet --list-runtimes
```

**Comment by Cryotechnic** [comment]
> Seems like your Runtime and SDK didn't get updated at the same time. Can you share the output of this command?
> 
> ```
> dotnet --list-sdks && dotnet --list-runtimes
> ```

![image](https://user-images.githubusercontent.com/9833218/209389442-88764850-1e0b-4273-b213-a25ce78ba57b.png)
Here you go, should be all of them.

**Comment by neon-nyan** [comment]
Have you tried to clean the build and then rebuild it?
Or maybe you can try downgrade the dependencies version that got updated before.

**Comment by Cryotechnic** [comment]
Turns out that deleting the repository and re-cloning it did the trick. I think it may have had something to do with you changing the name of the repository from `CollapseLauncher` to `Collapse`. Will close this for now but may reopen in the future if this issue arises again. Sorry for the trouble!
