### ISSUE TITLE
[Feature] Allow the app to restart itself if incorrect permission level

### ISSUE THREAD

**Issue by Cryotechnic** [neon-nyan/Collapse#67]
The application currently has no way of knowing if it is in the correct user scope, which can lead to some unwanted behavior when updating or launching the application and disabling admin rights. Currently, the following happens:

1. When updating to a newer release: 
- If the updater is not running with admin privileges, it is unable to write to `C:\Program Files\CollapseLauncher\_Temp`, which leads to the application crashing with an `UnauthorizedAccessException` error:
![image](https://user-images.githubusercontent.com/9833218/209452739-611938dd-bc76-43ad-a059-59fa6b148a09.png)
This issue will only arise if the user is not running Visual Studio 2022 under Admin mode, as not doing so makes the C# compiler run without admin arguments, therefore not allowing the application to write to the Program Files folder. 

The easiest workaround to fix this would be to simply run VS2022 in Administrator mode, but the best way to do it would be to have the program restart itself with admin rights through `Process.Kill()` and `Process.Start()` with `Verb = "runas"` as its launch parameters.

The reason that this is not an issue in production is because the pre-compiled binaries are compiled in administrator mode, so they have the correct permission levels set.
 
2. When launching Collapse:
- If Collapse is launched without having a correct version moniker (aka, the version of the launcher is NEWER than what is available) the launcher will launch, but the content will never render, and no exception will be thrown: 
![image](https://user-images.githubusercontent.com/9833218/209453157-9da08504-6e1b-4814-af39-3b23b3f72ff1.png)
![image](https://user-images.githubusercontent.com/9833218/209453172-e974294b-07e6-4357-b5b8-07a2a6bcc7fb.png)

If any of those issues arise, we should have the app prompt the user to restart it as admin, or restart itself as admin, either or works. This could prevent any issues from arising if there is an incorrect permission set somewhere.

**Comment by neon-nyan** [comment]
Making the app to run using administrator privilege permanently is actually possible for most of the case by adding ``requestedExecutionLevel`` into ``app.manifest`` file.
```
<requestedExecutionLevel  level="requireAdministrator" uiAccess="false" />
```
The problem is that the ``requestedExecutionLevel`` property seems to be conflicted with WindowsAppSDK's own ``app.manifest`` file and adding that line will give you an error while building the app.

To ensure that the app is always running under administrator privilege, can we put the implementation on the Start-up phase instead of the ``Update`` phase only?

**Comment by Cryotechnic** [comment]
As this has been implemented and is currently in [testing](https://github.com/neon-nyan/Collapse/releases/tag/CL-v1.0.64.0-pre), closing this issue for now.
