### ISSUE TITLE
[Enhancement] Implement selective download for updates

### ISSUE THREAD

**Issue by Cryotechnic** [neon-nyan/Collapse#69]
This means that the launcher should be able to recognize which files do not need to be downloaded and only download the newer files that it needs. 

Currently, each update, the launcher downloads ~180MB of new files to update the entire directory, but some files don't need to be re-downloaded (e.g. library files that did not receive updates, localization, etc.). 

One approach to this is to have a database of pre-compiled hashes stored locally and compare them to the remote hashes and download the difference. 

Another one would be to find something in C# (a library or a `System` call) to do the same thing.

This will probably require a major rewrite of the download mechanism but it saves on user bandwidth in the short and long-term.

**Comment by neon-nyan** [comment]
> One approach to this is to have a database of pre-compiled hashes stored locally and compare them to the remote hashes and download the difference.

I've actually done that approach but in each updates, It also contains changes from runtime (including .NET Core and WindowsAppSDK) causing the file size fluctuated.

I think, the easier way to do this is using delta patch like ``HDiffPatch`` and compare the difference for the last 4 old versions. What do you think?

**Comment by Cryotechnic** [comment]
I think the best way to implement this would be to use GitHub Actions or a CI/CD environment as we would be able to automate the release of new HDiffs instead of having to manually run them. 4 versions seems a bit excessive to me but I understand the need to want to keep older versions to rollback if necessary. In an ideal scenario, there could be the following:

- Latest
- Pre-release (Testing)
- Last major software revision (minus Latest)
- Last minor software revision (minus Latest)

The end-goal of this implementation would be to have a hands-free update experience from the developer's and user's side. The user already gets automatic update notifications, however, implementing this on the developer's side would require us to integrate the HDiffPatch binary in our build from now on, which I am unsure how to integrate at this point in time, but I'll do some digging on my end.

This also has the added benefit of generating preview builds in real-time and updating the README accordingly with the new version number generated during the CI/CD pipeline. 

I can try playing around with it and seeing if I can integrate it on my end, but without knowing how the current patch fetch works on the client, I would need you to point me in the right direction.

Aside from that, excited to finally start working on this!

**Comment by Cryotechnic** [comment]
@neon-nyan It's been a while since this issue was opened, so going to provide an update on this for the general public. We're currently in the process of testing [Squirrel](https://github.com/Squirrel/Squirrel.Windows), which is a powerful update manager used by popular applications such as Discord, Microsoft and the such.

Squirrel works by utilizing NuGet and generating a packaged version of our application, as well as generating delta patch files required to patch our application to the newer version. The upside is that this reduces bandwidth cost after the initial download by over 80% (full update package ~70MB, delta ~200KB). This allows us to quickly distribute updates, more frequently, with less bandwidth saturation on our CDN providers and on the GitHub update repository.

There is no action required on the users' end. This feature will ship with the next major release of Collapse (1.69). Stay tuned for development updates!

**Comment by Cryotechnic** [comment]
This feature has now shipped as part of update 1.69.7: Codename Kiana.

Thank you for your patience!
