### ISSUE TITLE
[Suggestion] Implement correct scaling for 3:4 monitors

### ISSUE THREAD

**Issue by Cryotechnic** [neon-nyan/Collapse#76]
Currently, the launcher starts with a fixed width and height (1196x726) which works fine for 16:9 monitors, but breaks when the monitor is smaller than the defined parameters. The solution to this would be to determine display specifications through [`System.Windows.SystemParameters`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.systemparameters?view=windowsdesktop-7.0) and to then scale the elements accordingly.

Main reason for this is that my, [Framework Laptop](https://frame.work), sports a 3:2 display, which causes the application to have part of the application window initially appear out of bounds. Resizing the application fixes the issue but it would be nice if Collapse could scale to the display.

![image](https://user-images.githubusercontent.com/9833218/214447196-c5566b12-1c09-4477-91dd-e43d14177ef8.png)

![image](https://user-images.githubusercontent.com/9833218/214446736-24f9c25a-30b7-4afc-9e2a-e7c99a43aed2.png)

**Comment by neon-nyan** [comment]
Sorry for my very late reply on this.
I think, we can implement some options to give users a choose the size of the launcher window.
Unfortunately, this doesn't include a support for resizing in free-form.

**Comment by Cryotechnic** [comment]
> Sorry for my very late reply on this. I think, we can implement some options to give users a choose the size of the launcher window. Unfortunately, this doesn't include a support for resizing in free-form.

That makes sense, as some elements should have a defined size. I think this can be added in the `Launcher Settings` as well as during the initial setup? Let me know what you think.

**Comment by neon-nyan** [comment]
> That makes sense, as some elements should have a defined size. I think this can be added in the `Launcher Settings` as well as during the initial setup? Let me know what you think.

I've just added a setting in App Settings page to adjust window size.
For now, only two sizes are available, which are:
- Normal (1196x726 px)
- Small (1028x622 px)

https://user-images.githubusercontent.com/30566970/222958864-be17f7b2-f942-46ca-ae3c-fd883506c78b.mp4

**Comment by neon-nyan** [comment]
Closing this issue for now as the feature has been implemented in recent commit and will be shipped in the next preview version
