### ISSUE TITLE
[Tracking] Implement Honkai: Star Rail as a supported game

### ISSUE THREAD

**Issue by Cryotechnic** [neon-nyan/Collapse#78]
As of today, Honkai: Star Rail has opened up pre-registration for their game. While the game itself is not listed to come out before April 26th, it is good to make previsions as Collapse is a launcher for all miHoYo titles. This issue is meant to track all the different tasks that are required in order to properly implement HSR into Collapse before or after its release. It's also meant to not have 30 different issues that will get created about adding this game to our supported game list XD.

Feel free to pin this for tracking purposes. @neon-nyan 

Edit 2023-02-21: An early implementation of HSR support is complete. To access it, you need to modify Collapse's `metadatav2.json` file. These modifications are not made public on purpose due to the launcher's instability and missing featureset for HSR. These features will be gradually implemented and rolled out to the public in due time and should make the launcher ready for HSR's release in April (tentative as MHY has not yet given us an official launch date). **Don't ask for access.** Regular users will just magically see HSR appear in their supported list once testing is complete and the game is released!

Edit 2023-04-05: Collapse will ship with support for Honkai: Star Rail in version 1.69.0, which will release imminently. As stated before, users do not need to do anything and simply need to wait until we enable it on our end!

**Comment by neon-nyan** [comment]
Hi @Cryotechnic,

I'm agree and "**Launcher for all miHoYo Games**" is a better vision for Collapse currently. I'm also on the way to implementing a support for Honkai: Star Rail and might be started tomorrow (Saturday) once I get some of my free time.

Might be pushing the implementation branch tomorrow

**Comment by Cryotechnic** [comment]
> Hi @Cryotechnic,
> 
> I'm agree and "**Launcher for all miHoYo Games**" is a better vision for Collapse currently. I'm also on the way to implementing a support for Honkai: Star Rail and might be started tomorrow (Saturday) once I get some of my free time.
> 
> Might be pushing the implementation branch tomorrow

I'm trying to get my hands on a beta access for the game, so will keep you posted if I do. Let me know if there is anything you want me to track, download-wise (URLs, etc.) as well as what steps to take to get that information.

**Comment by neon-nyan** [comment]
You can join Ironmaiden's Armada Discord. You can click on "Join our Armada Discord Server" in the App Settings menu. We have a dedicated channel to talk about IT and stuff in #coder-lab.

You can find me as "wasA🅱️e-kun" there.

**Comment by Cryotechnic** [comment]
Honkai: Star Rail preload is out, and so is Collapse's support for it! Make sure that your launcher is running the latest version and has updated metadata. See you aboard, Trailblazers!
