### ISSUE TITLE
[Feature] Allow Switching from Dev to Stable inside Collapse

### ISSUE THREAD

**Issue by Cryotechnic** [neon-nyan/Collapse#86]
Implement a way to switch branches, either through a button toggle or through a dropdown. Selecting the other option would force a restart of the launcher and an update to the latest compiled branch build (most likely a complete redownload until we figure out a way to use `HDiff`.

**Comment by neon-nyan** [comment]
Closing this for now as this already implemented in memory-squash branch and will be shipped in the next preview version
