### ISSUE TITLE
[Feature Request] Account Switcher

### ISSUE THREAD

**Issue by seriaati** [neon-nyan/Collapse#88]
An account switcher for Genshin Impact like [this launcher](https://github.com/DawnFz/Genshin.Launcher.Plus).

**Comment by bagusnl** [comment]
Already discussed on #65

**Comment by seriaati** [comment]
No, an account switcher doesn't necessarily mean that the authentication process needs to be done on Collapse's end. If you look at [the repo I provided above](https://github.com/DawnFz/Genshin.Launcher.Plus), there seems to be a file saved locally that contains account information to allow account switching.

So the user actually logs in the account first (authentication process done by Hoyoverse) -> Then the user can choose to "save" the current logged in account (by saving a file or something similar) -> Then switch accounts by switching the file that contains account information.

Please seriously consider adding this because it's such an important feature that Hoyoverse's current launcher doesn't have.

**Comment by tilsgee** [comment]
> Already discussed on #65 

Still disagree..

OP already provide similar open source HYV launcer with switch account support.

**Comment by muscularcandy67** [comment]
> No, an account switcher doesn't necessarily mean that the authentication process needs to be done on Collapse's end. If you look at [the repo I provided above](https://github.com/DawnFz/Genshin.Launcher.Plus), there seems to be a file saved locally that contains account information to allow account switching.
> 
> So the user actually logs in the account first (authentication process done by Hoyoverse) -> Then the user can choose to "save" the current logged in account (by saving a file or something similar) -> Then switch accounts by switching the file that contains account information.
> 
> Please seriously consider adding this because it's such an important feature that Hoyoverse's current launcher doesn't have.

The main reason why most official launchers don't have an account switcher is simple. You mainly use one account and done. It's rare for normal people to have multiple accounts, unless your purpose is to create an indefinite amount of accounts and reroll to get multiple 5* on first pull, which is petty imo, or helping a friend when they can't log in for a short amount of time. Also, mhy handles login in game, not on launcher. If it gets implemented in Collapse, the whole project will be at huge risk of being banned, and it's probably something all of us don't want.

**Comment by seriaati** [comment]
This is my understanding of your points regarding why you think an account switcher feature should not be added:

1. Small use-case
You mentioned that most people "mainly use on account and done", this point can be largely biased based on one's point of view. For me, many friends around me play on more than 1 account, and I assume that it feels rational for you that people only play on 1 account because either you or people around you don't play on multiple accounts. While we can't get the exact statistics of how many players in Genshin Impact play on more than 1 account, I can guarantee that the number is not small. Personally, my use-case is to play on my friends' accounts and sometimes do dailies for other people. Another major use-case that I know is to play on different servers, many players have already reached the end-game phase so they'd like to have a fresh restart. I strongly disagree with this point.

2. High risk feature
I agree with this, I indeed don't want to see an amazing project like Collapse to get shut down by Hoyoverse because of adding this feature. However, is it true that adding account switcher = Collapse shut down? First, we can look at [this repo](https://github.com/DawnFz/Genshin.Launcher.Plus). It has 765 stars right now and the launcher existed for a very long period of time. While the fact that this launcher is not shut down yet doesn't necessarily mean that an account switcher is Okay, I think it's still reasonable to use it as a reference. (Not to mention that it even has a FPSUnlocker feature, which is clearly prohibited by Hoyoverse).

**Comment by bagusnl** [comment]
As author described in the last thread about this, its not a planned feature to be implemented in this launcher. A little read to [Genshin's Legal FAQ ](https://www.hoyolab.com/article/143107) about this:

> 5. Can I put programs for updating miHoYo games on a website of my choice so others can download them?
>> No. To protect the security of our users' accounts, miHoYo strictly forbids users from making update programs available on unauthorized third-party platforms. miHoYo reserves the right to terminate any and all agreements with any users who are found to be in violation of this rule at its sole discretion. miHoYo reserves the right to refuse unauthorized third-party platforms from hosting, disseminating, or distributing miHoYo product-related programs for any reason and at any time.

While we do understand that this launcher already broke this point, adding more feature that touches their SDK (registry key for the account change is MIHOYOSDK_PROD_OVERSEA_x) will add more point towards their claim, if they decides to (try) strike this project.
We also have to remember that this project is not just launcher for Genshin, it also used to launch another HYV games such as HI3, which the main motivation for the author making this project. The game sometime suffers with cache issues and other inconveniences regarding the game that this launcher fix. 

While I (and project maintainers I often talk to) do see the usefulness of this feature, its quite hard to come for the conclusion of implementing this feature or not, knowing the risk that it might have towards the project. Of course, the author might change his mind and re-think about this feature in the future.

**Comment by seriaati** [comment]
Understood, I respect the project owner's decision.

**Comment by neon-nyan** [comment]
Hi @seriaati, @tilsgee and all contributors who helped me on this,

First of all, thank you so much for your question in this issue.
I understand that you need this feature to be implemented. Actually, this is really easy for me to implement this.
But on the other side, I have a concern by accessing user's confidential data, means I may possibly compromise their data.

As part as this is also **_not planned_** and I believe that this launcher already crossed the line of miHoYo's T&Cs. We don't want to make this beyond the limit as you might already heard that most of the projects that took "as a result of reverse engineering" went gone (since this launcher is a result of that and some feature in this project uses it).
We are avoiding to bring this project into miHoYo's attention and we don't want to give this project the same fate.

I really appreciate your feedback on this launcher and thank you so much for trying this out.
But as I already said before,... we are sorry that we can't bring this feature alive to this launcher based on the reasons above.

Hope this could answer some of your questions.
